### ISSUE TITLE
Missing state_type_e get_state() const in application interface

### ISSUE THREAD

**Issue by ManuelKugelmann** [COVESA/vsomeip#101]
When some user code gets an app handle after the app is started, there is no direct option to get the app state. Adding state_type_e get_state() const to the application interface would solve this.
Another option would be to directly call the state handler just when it gets attached in case the app was already ready.

(Of course the code responsible for starting the app could register a state handler and cache the current app state to provide it to other user code, but this is not straight forward.)

**Comment by goncaloalmeida** [comment]
hello @ManuelKugelmann 
indeed we don't have this state because we never needed it.
Feel free to create a PR to add it if you want.
One note: This new state will require an update to the minor version.
