### ISSUE TITLE
vsomeip3*.lib not installed on windows except for vsomeip3.lib

### ISSUE THREAD

**Issue by mkadavil** [COVESA/vsomeip#130]
The .libs are installed on windows when ARCHIVE DESTINATION "${INSTALL_LIB_DIR}" is part of the install command in CMakelists.txt. Only for vsomeip3 (install( TARGETS ${VSOMEIP_NAME}..) )target was this the case.

**Comment by goncaloalmeida** [comment]
@mkadavil this problem still occur?

**Comment by goncaloalmeida** [comment]
Closing the ticket -> if the problem still occurs please reopen the ticket.
