### ISSUE TITLE
service  is not available now, but we may receivce the service data

### ISSUE THREAD

**Issue by ByteXiaoTang** [COVESA/vsomeip#170]
### the question is the service  is not available now, but we may receivce the service data
* if first handler_type_e::AVAILABILITY data that is not availbale type now is solving.
then, the second handler_type_e::AVAILABILITY data that is available type  is comming, the data should be pending.
function will solve the third data, which may be handler_type_e::MESSAGE. and the data will solved immediately.
the question is the service  is not available now, but we may receivce the service data

<img width="561" alt="sequence_error" src="https://user-images.githubusercontent.com/32772277/98339863-5eca1180-2047-11eb-9b6e-52e28fb7c50c.png">

**Comment by lutzbichler** [comment]
I am afraid I do not really understand. If I read the code correctly, all handlers are rescheduled until all availability handlers for the same service instance have been executed.

**Comment by ByteXiaoTang** [comment]
all availability handlers are sequenced， but messages are not in the same sequence with the availability handlers sequence. we may solve message when service is unavailable solving.

**Comment by goncaloalmeida** [comment]
Please provide an example using the last version (3.0.0) of why you need this.
