### ISSUE TITLE
pending_sd_offers_.erase(it) break may error

### ISSUE THREAD

**Issue by ByteXiaoTang** [COVESA/vsomeip#186]
std::vector<std::pair<service_t, instance_t>> pending_sd_offers_;
if find one, break used. in fact,  we may erase all in the vector.
![image](https://user-images.githubusercontent.com/32772277/100495734-76e60a00-3189-11eb-9e43-4b3502ccb61f.png)

**Comment by lutzbichler** [comment]
Pending offers are inserted on "offer_service", if there hasn´t been an offer command already (checked by insert_offer_command).  Thus, pending_sd_offers_ will not contain the same (service, instance) tuple twice.
Am I missing something?

**Comment by ByteXiaoTang** [comment]
in fact, we may not check before insert
![image](https://user-images.githubusercontent.com/32772277/101463430-5df30b00-3978-11eb-9c0b-28d15ee20e70.png)

**Comment by goncaloalmeida** [comment]
Please provide an example using the last version (3.0.0) of why you need this.
