### ISSUE TITLE
the request client_ may error

### ISSUE THREAD

**Issue by ByteXiaoTang** [COVESA/vsomeip#198]
in fact ,we should use client_ = utility::request_client_id(configuration_, name_, client_) instead of 
utility::request_client_id(configuration_, name_, client_);
because the client_ may return the next_client__ which we actually use
![image](https://user-images.githubusercontent.com/32772277/102845287-3146f500-4448-11eb-8b2c-25389f43bac2.png)

**Comment by lutzbichler** [comment]
Correct. Will be changed in the next version.

**Comment by goncaloalmeida** [comment]
Fixed on version 3.3.0 (master branch).
