### ISSUE TITLE
is_stop_subscribe_subscribe use may error

### ISSUE THREAD

**Issue by ByteXiaoTang** [COVESA/vsomeip#204]
we use     if (is_stop_subscribe_subscribe) {
                        force_initial_events = true;
                    }

![image](https://user-images.githubusercontent.com/32772277/103337273-b61fb780-4ab5-11eb-80c9-8f25a418937e.png)

we may use like next:
![image](https://user-images.githubusercontent.com/32772277/103337359-07c84200-4ab6-11eb-92b0-c55f67deb336.png)

**Comment by lutzbichler** [comment]
We need to force initial events in case of STOP SUBSCRIBE / SUBSCRIBE. Therefore, we use the check result of the preceeding entry to decide.
