### ISSUE TITLE
check_stop_subscribe_subscribe question

### ISSUE THREAD

**Issue by ByteXiaoTang** [COVESA/vsomeip#207]
![image](https://user-images.githubusercontent.com/32772277/103618452-f3c78900-4f6a-11eb-8213-d79595594089.png)
why  (*its_next)->get_type() != entry_type_e::SUBSCRIBE_EVENTGROUP)

**Comment by goncaloalmeida** [comment]
Please provide an example using the last version (3.0.0) of why you need this.
