### ISSUE TITLE
send_uni_or_multicast_offerservice question

### ISSUE THREAD

**Issue by ByteXiaoTang** [COVESA/vsomeip#212]
![image](https://user-images.githubusercontent.com/32772277/104552837-7e4b6f00-5674-11eb-9d41-1dfcee47c397.png)

i may not understand why _unicast_flag is false, then send_unicast_offer_service.

**Comment by tjpsantiago16** [comment]
Hi @lutzbichler,

Is this a bug in the code? As stated above it is quite confusing that send_unicast_offer_service is used when _unicast_flag is false.

**Comment by goncaloalmeida** [comment]
Please provide an example using the last version (3.0.0) of why you need this.
