### ISSUE TITLE
[error] netlink_connector::receive_cbk received error message: 2 seq 2

### ISSUE THREAD

**Issue by ChezzPlaya** [COVESA/vsomeip#214]
I receive sometimes this error message.

What does it mean? Can someone maybe explain, it?

**Comment by lecea** [comment]
我也是一样的错误

**Comment by shubhamck** [comment]
मया अपि तथैव दोषः प्राप्तः

**Comment by goncaloalmeida** [comment]
@ChezzPlaya This problem is still occurring?

**Comment by ChezzPlaya** [comment]
> @ChezzPlaya This problem is still occurring?

I don't care anymore.
