### ISSUE TITLE
Cannot able to build on Windows with MinGW compiler.

### ISSUE THREAD

**Issue by jeinil-patel** [COVESA/vsomeip#215]
I have tried to build 3.1.14 with MinGW 4.8.0 and boost 1.70. My machine configuration is Windows 64bit. I am getting declaration error in "server_endpoint_impl.cpp". Anyone can help? 

**Boost build**

![boost_install](https://user-images.githubusercontent.com/68753333/104741344-5da11900-5749-11eb-867a-4839daa57d86.png)

**Build log**

![libraries](https://user-images.githubusercontent.com/68753333/104741454-87f2d680-5749-11eb-9f01-39f8a0ad8777.png)

**Error**

![Error](https://user-images.githubusercontent.com/68753333/104741574-b1abfd80-5749-11eb-8c32-ea7401892c28.png)

**Comment by goncaloalmeida** [comment]
We currently do not support mingw builds. suggestion -> MSVC
