### ISSUE TITLE
subscribe when discovery_  is not null question

### ISSUE THREAD

**Issue by ByteXiaoTang** [COVESA/vsomeip#217]
![image](https://user-images.githubusercontent.com/32772277/104886684-1a42e680-59a5-11eb-9524-f1762e9e15e2.png)

when discovery_ is not nullptr and its_local_client is not 0. then we try to use stub_->send_subscribe.
why has the condition?
if we use the stub_->send_subscribe. i think we need  not care of the value of discovery_. But in the coding, we may only try to use stub_->send_subscribe when discovery_ is not null.

**Comment by goncaloalmeida** [comment]
Please provide an example using the last version (3.0.0) of why you need this.
