### ISSUE TITLE
client_routing_info_.erase question

### ISSUE THREAD

**Issue by ByteXiaoTang** [COVESA/vsomeip#221]
![image](https://user-images.githubusercontent.com/32772277/105698926-93ac7d00-5f41-11eb-9466-abaff0196eb8.png)

when its_endpoint is nullptr, we also need use client_routing_info_.erase(_target) . because some old data may in the client_routing_info_ map.

**Comment by goncaloalmeida** [comment]
Please provide an example using the last version (3.0.0) of why you need this.
