### ISSUE TITLE
client_size may change 

### ISSUE THREAD

**Issue by ByteXiaoTang** [COVESA/vsomeip#224]
![image](https://user-images.githubusercontent.com/32772277/106084578-8ff34300-6159-11eb-9175-02701b42cdf3.png)
   while (j + sizeof(uint32_t) <= its_client_size)  should be    while (j + sizeof(uint32_t) <= its_client_size -2 ) 
because client has two bytes.

**Comment by fcmonteiro** [comment]
Hi @ByteXiaoTang,
Can you explain better the issue?
Also is this relevant to vSomeIP 3.3?
Thanks

cc: @goncaloalmeida
