### ISSUE TITLE
use  std::condition_variable  which affect by system time change

### ISSUE THREAD

**Issue by ByteXiaoTang** [COVESA/vsomeip#248]
![image](https://user-images.githubusercontent.com/32772277/118101026-b9cf2d80-b409-11eb-8d07-a1fa6434328a.png)
suggest not use condition_variable wait_for which will affect by system time change

**Comment by fcmonteiro** [comment]
Hi @ByteXiaoTang,
Any suggestion on what to use instead of wait_for?
Thanks
