### ISSUE TITLE
IPV4 Multicast Option 

### ISSUE THREAD

**Issue by mouadhgit** [COVESA/vsomeip#275]
I m trying to see the IPV4 multicast option at the Subscribe_Event _groupe_ack message using Wireshark but the length of options is always 0 ! so I can't see the IPV4 multicast option, Although I am adding the multicast option true at the .json file.
I'm running the notify/subscribe example offered by the stack.
i will be thankful for any helps

**Comment by ims0** [comment]
server  configuration of multicast  as follow
   "eventgroups" :
            [
                {
                    "eventgroup" : "0x0001",
                    "events" : [  "0x9001" ],
                    "threshold" : "1",
                    "multicast" :
                    {
                        "address" : "224.224.224.245",
                        "port" : "32344"
                    }
                }
            ]
