### ISSUE TITLE
compile issue in AOSP

### ISSUE THREAD

**Issue by naocanyouji** [COVESA/vsomeip#282]
when building library libvsomeip3-cfg with android.bp in AOSP, some errors happened, these are error logs, can someone help fix?

ld.lld: error: undefined symbol: boost::filesystem::detail::directory_iterator_construct(boost::filesystem::directory_iterator&, boost::filesystem::path const&, boost::system::error_code*)
>>> referenced by operations.hpp:957 (external/vsomeip/vsomeip-master/external/boost_1_70/include/boost/filesystem/operations.hpp:957)
>>>               out/soong/.intermediates/external/vsomeip/vsomeip-master/libvsomeip3-cfg/android_vendor.30_arm64_armv8-a_shared/obj/external/vsomeip/vsomeip-master/implementation/configuration/src/configuration_impl.o:(vsomeip_v3::cfg::configuration_impl::read_data(std::__1::set<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::vector<vsomeip_v3::configuration_element, std::__1::allocator<vsomeip_v3::configuration_element> >&, std::__1::set<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&, bool))

**Comment by nkh-lab** [comment]
Do you have Boost libraries in your AOSP?

**Comment by nkh-lab** [comment]
Like example you can use this AOSP manifest project where vsomeip and boost libraries are built in: [https://github.com/nkh-lab/aosp-ncar-manifest](https://github.com/nkh-lab/aosp-ncar-manifest). Just sync, compile AOSP, compile [vsomeip hello_world example](https://github.com/COVESA/vsomeip/tree/master/examples/hello_world) and run it on emulator.

**Comment by ByteXiaoTang** [comment]
Boost not right

**Comment by ByteXiaoTang** [comment]
git clone -b boost-1.70.0 git@github.com:boostorg/accumulators.git
git clone -b boost-1.70.0 git@github.com:boostorg/algorithm.git
git clone -b boost-1.70.0 git@github.com:boostorg/align.git
git clone -b boost-1.70.0 git@github.com:boostorg/any.git
git clone -b boost-1.70.0 git@github.com:boostorg/array.git
git clone -b boost-1.70.0 git@github.com:boostorg/asio.git
git clone -b boost-1.70.0 git@github.com:boostorg/assert.git
git clone -b boost-1.70.0 git@github.com:boostorg/assign.git
git clone -b boost-1.70.0 git@github.com:boostorg/atomic.git
git clone -b boost-1.70.0 git@github.com:boostorg/beast.git
git clone -b boost-1.70.0 git@github.com:boostorg/bimap.git
git clone -b boost-1.70.0 git@github.com:boostorg/bind.git
git clone -b boost-1.70.0 git@github.com:boostorg/callable_traits.git
git clone -b boost-1.70.0 git@github.com:boostorg/chrono.git
git clone -b boost-1.70.0 git@github.com:boostorg/circular_buffer.git
git clone -b boost-1.70.0 git@github.com:boostorg/compatibility.git
git clone -b boost-1.70.0 git@github.com:boostorg/compute.git
git clone -b boost-1.70.0 git@github.com:boostorg/concept_check.git
git clone -b boost-1.70.0 git@github.com:boostorg/config.git
git clone -b boost-1.70.0 git@github.com:boostorg/container.git
git clone -b boost-1.70.0 git@github.com:boostorg/container_hash.git
git clone -b boost-1.70.0 git@github.com:boostorg/context.git
git clone -b boost-1.70.0 git@github.com:boostorg/conversion.git
git clone -b boost-1.70.0 git@github.com:boostorg/convert.git
git clone -b boost-1.70.0 git@github.com:boostorg/core.git
git clone -b boost-1.70.0 git@github.com:boostorg/coroutine.git
git clone -b boost-1.70.0 git@github.com:boostorg/coroutine2.git
git clone -b boost-1.70.0 git@github.com:boostorg/crc.git
git clone -b boost-1.70.0 git@github.com:boostorg/date_time.git
git clone -b boost-1.70.0 git@github.com:boostorg/detail.git
git clone -b boost-1.70.0 git@github.com:boostorg/disjoint_sets.git
git clone -b boost-1.70.0 git@github.com:boostorg/dll.git
git clone -b boost-1.70.0 git@github.com:boostorg/dynamic_bitset.git
git clone -b boost-1.70.0 git@github.com:boostorg/endian.git
git clone -b boost-1.70.0 git@github.com:boostorg/exception.git
git clone -b boost-1.70.0 git@github.com:boostorg/fiber.git
git clone -b boost-1.70.0 git@github.com:boostorg/filesystem.git
git clone -b boost-1.70.0 git@github.com:boostorg/flyweight.git
git clone -b boost-1.70.0 git@github.com:boostorg/foreach.git
git clone -b boost-1.70.0 git@github.com:boostorg/format.git
git clone -b boost-1.70.0 git@github.com:boostorg/function.git
git clone -b boost-1.70.0 git@github.com:boostorg/functional.git
git clone -b boost-1.70.0 git@github.com:boostorg/function_types.git
git clone -b boost-1.70.0 git@github.com:boostorg/fusion.git
git clone -b boost-1.70.0 git@github.com:boostorg/geometry.git
git clone -b boost-1.70.0 git@github.com:boostorg/gil.git
git clone -b boost-1.70.0 git@github.com:boostorg/graph.git
git clone -b boost-1.70.0 git@github.com:boostorg/graph_parallel.git
git clone -b boost-1.70.0 git@github.com:boostorg/hana.git
git clone -b boost-1.70.0 git@github.com:boostorg/heap.git
git clone -b boost-1.70.0 git@github.com:boostorg/icl.git
git clone -b boost-1.70.0 git@github.com:boostorg/integer.git
git clone -b boost-1.70.0 git@github.com:boostorg/interprocess.git
git clone -b boost-1.70.0 git@github.com:boostorg/intrusive.git
git clone -b boost-1.70.0 git@github.com:boostorg/io.git
git clone -b boost-1.70.0 git@github.com:boostorg/iostreams.git
git clone -b boost-1.70.0 git@github.com:boostorg/iterator.git
git clone -b boost-1.70.0 git@github.com:boostorg/lambda.git
git clone -b boost-1.70.0 git@github.com:boostorg/lexical_cast.git
git clone -b boost-1.70.0 git@github.com:boostorg/locale.git
git clone -b boost-1.70.0 git@github.com:boostorg/local_function.git
git clone -b boost-1.70.0 git@github.com:boostorg/lockfree.git
git clone -b boost-1.70.0 git@github.com:boostorg/log.git
git clone -b boost-1.70.0 git@github.com:boostorg/logic.git
git clone -b boost-1.70.0 git@github.com:boostorg/math.git
git clone -b boost-1.70.0 git@github.com:boostorg/metaparse.git
git clone -b boost-1.70.0 git@github.com:boostorg/move.git
git clone -b boost-1.70.0 git@github.com:boostorg/mp11.git
git clone -b boost-1.70.0 git@github.com:boostorg/mpi.git
git clone -b boost-1.70.0 git@github.com:boostorg/mpl.git
git clone -b boost-1.70.0 git@github.com:boostorg/msm.git
git clone -b boost-1.70.0 git@github.com:boostorg/multi_array.git
git clone -b boost-1.70.0 git@github.com:boostorg/multi_index.git
git clone -b boost-1.70.0 git@github.com:boostorg/multiprecision.git
git clone -b boost-1.70.0 git@github.com:boostorg/numeric_conversion.git
git clone -b boost-1.70.0 git@github.com:boostorg/optional.git
git clone -b boost-1.70.0 git@github.com:boostorg/parameter.git
git clone -b boost-1.70.0 git@github.com:boostorg/phoenix.git
git clone -b boost-1.70.0 git@github.com:boostorg/poly_collection.git
git clone -b boost-1.70.0 git@github.com:boostorg/polygon.git
git clone -b boost-1.70.0 git@github.com:boostorg/pool.git
git clone -b boost-1.70.0 git@github.com:boostorg/predef.git
git clone -b boost-1.70.0 git@github.com:boostorg/preprocessor.git
git clone -b boost-1.70.0 git@github.com:boostorg/process.git
git clone -b boost-1.70.0 git@github.com:boostorg/program_options.git
git clone -b boost-1.70.0 git@github.com:boostorg/property_map.git
git clone -b boost-1.70.0 git@github.com:boostorg/property_tree.git
git clone -b boost-1.70.0 git@github.com:boostorg/proto.git
git clone -b boost-1.70.0 git@github.com:boostorg/ptr_container.git
git clone -b boost-1.70.0 git@github.com:boostorg/python.git
git clone -b boost-1.70.0 git@github.com:boostorg/qvm.git
git clone -b boost-1.70.0 git@github.com:boostorg/random.git
git clone -b boost-1.70.0 git@github.com:boostorg/range.git
git clone -b boost-1.70.0 git@github.com:boostorg/ratio.git
git clone -b boost-1.70.0 git@github.com:boostorg/rational.git
git clone -b boost-1.70.0 git@github.com:boostorg/regex.git
git clone -b boost-1.70.0 git@github.com:boostorg/scope_exit.git
git clone -b boost-1.70.0 git@github.com:boostorg/serialization.git
git clone -b boost-1.70.0 git@github.com:boostorg/signals.git
git clone -b boost-1.70.0 git@github.com:boostorg/signals2.git
git clone -b boost-1.70.0 git@github.com:boostorg/smart_ptr.git
git clone -b boost-1.70.0 git@github.com:boostorg/sort.git
git clone -b boost-1.70.0 git@github.com:boostorg/spirit.git
git clone -b boost-1.70.0 git@github.com:boostorg/stacktrace.git
git clone -b boost-1.70.0 git@github.com:boostorg/statechart.git
git clone -b boost-1.70.0 git@github.com:boostorg/static_assert.git
git clone -b boost-1.70.0 git@github.com:boostorg/system.git
git clone -b boost-1.70.0 git@github.com:boostorg/test.git
git clone -b boost-1.70.0 git@github.com:boostorg/thread.git
git clone -b boost-1.70.0 git@github.com:boostorg/throw_exception.git
git clone -b boost-1.70.0 git@github.com:boostorg/timer.git
git clone -b boost-1.70.0 git@github.com:boostorg/tokenizer.git
git clone -b boost-1.70.0 git@github.com:boostorg/tti.git
git clone -b boost-1.70.0 git@github.com:boostorg/tuple.git
git clone -b boost-1.70.0 git@github.com:boostorg/type_erasure.git
git clone -b boost-1.70.0 git@github.com:boostorg/type_index.git
git clone -b boost-1.70.0 git@github.com:boostorg/typeof.git
git clone -b boost-1.70.0 git@github.com:boostorg/type_traits.git
git clone -b boost-1.70.0 git@github.com:boostorg/units.git
git clone -b boost-1.70.0 git@github.com:boostorg/unordered.git
git clone -b boost-1.70.0 git@github.com:boostorg/utility.git
git clone -b boost-1.70.0 git@github.com:boostorg/uuid.git
git clone -b boost-1.70.0 git@github.com:boostorg/variant.git
git clone -b boost-1.70.0 git@github.com:boostorg/vmd.git
git clone -b boost-1.70.0 git@github.com:boostorg/wave.git
git clone -b boost-1.70.0 git@github.com:boostorg/winapi.git
git clone -b boost-1.70.0 git@github.com:boostorg/xpressive.git

then .check to the tags。。。
then use the following android.bp to compilie..
cc_defaults {
    name: "boost_defaults",
    vendor: true,
//    vendor_available: true,
}
cc_defaults {
    name: "boost_headers_defaults",
    defaults: ["boost_defaults"],
}
cc_defaults {
    name: "boost_library_defaults",
    defaults: ["boost_defaults"],
    rtti: true,
    cflags: [
        "-Wall",
//        "-Werror",
        "-fexceptions",
//        "-DBOOST_THREAD_DONT_USE_CHRONO",
//        "-DBOOST_THREAD_POSIX",
        "-DBOOST_ASIO_HAS_STD_STRING_VIEW",
    ],
}
cc_library_headers {
    name: "libboost_headers",
    defaults: ["boost_headers_defaults"],
    export_include_dirs: [
        "accumulators/include/",
        "algorithm/include/",
        "align/include/",
        "any/include/",
        "array/include",
        "asio/include/",
        "assert/include",
        "assign/include",
        "atomic/include",
        "beast/include",
        "bimap/include",
        "bind/include/",
        "callable_traits/include/",
        "chrono/include",
        "circular_buffer/include",
        "compatibility/include",
        "compute/include",
        "concept_check/include",
        "config/include",
        "container/include",
        "container_hash/include",
        "context/include",
        "conversion/include",
        "convert/include",
        "core/include",
        "coroutine/include",
        "coroutine2/include",
        "crc/include",
        "date_time/include",
        "detail/include",
        "disjoint_sets/include",
        "dll/include",
        "dynamic_bitset/include",
        "endian/include",
        "exception/include",
        "fiber/include",
        "filesystem/include",
        "flyweight/include",
        "foreach/include/",
        "format/include/",
        "function/include/",
        "functional/include/",
        "function_types/include/",
        "fusion/include",
        "geometry/include",
        "gil/include",
        "graph/include",
        "graph_parallel/include",
        "hana/include",
        "heap/include",
        "icl/include",
        "integer/include",
        "interprocess/include/",
        "intrusive/include",
        "io/include",
        "iostreams/include",
        "iterator/include",
        "lambda/include",
        "lexical_cast/include/",
        "locale/include",
        "local_function/include",
        "lockfree/include",
        "log/include",
        "logic/include",
        "math/include",
        "metaparse/include",
        "move/include",
        "mp11/include",
        "mpi/include",
        "mpl/include",
        "msm/include",
        "multi_array/include",
        "multi_index/include/",
        "multiprecision/include/",
//        "numeric/include",
        "numeric_conversion/include",
        "optional/include",
        "parameter/include",
        "phoenix/include",
        "poly_collection/include",
        "polygon/include",
        "pool/include",
        "predef/include",
        "preprocessor/include",
        "process/include",
        "program_options/include",
        "property_map/include",
        "property_tree/include/",
        "proto/include",
        "ptr_container/include",
        "python/include",
        "qvm/include",
        "random/include",
        "range/include",
        "ratio/include",
        "rational/include",
        "regex/include",
        "scope_exit/include",
        "serialization/include",
//        "signals/include",
        "signals2/include",
        "smart_ptr/include",
        "sort/include",
        "spirit/include",
        "stacktrace/include",
        "statechart/include",
        "static_assert/include",
        "system/include",
        "test/include",
        "thread/include",
        "throw_exception/include",
        "timer/include",
        "tokenizer/include/",
        "tti/include/",
        "tuple/include/",
        "type_erasure/include",
        "type_index/include",
        "typeof/include/",
        "type_traits/include",
        "units/include",
        "unordered/include",
        "utility/include",
        "uuid/include",
        "variant/include/",
        "vmd/include/",
        "wave/include/",
        "winapi/include/",
        "xpressive/include/",
    ]
}
cc_library {
    name: "libboost_chrono",
    defaults: ["boost_library_defaults"],
    header_libs: [
        "libboost_headers",
    ],
    shared: {
        shared_libs: [
            "libboost_system",
        ],
    },
    srcs : [
        "chrono/src/**/*.cpp",
    ],
    export_include_dirs: ["chrono/include"],
    export_header_lib_headers: [
        "libboost_headers",
    ],
}
cc_library {
    name: "libboost_date_time",
    defaults: ["boost_library_defaults"],
    header_libs: [
        "libboost_headers",
    ],
    srcs : [
        "date_time/src/**/*.cpp",
    ],
    export_include_dirs: ["date_time/include"],
    export_header_lib_headers: [
        "libboost_headers",
    ],
}
cc_library {
    name: "libboost_filesystem",
    defaults: ["boost_library_defaults"],
    //FIXME: build workaround
    cflags: [
        "-Wno-deprecated-declarations",
        "-Wno-non-virtual-dtor",
        "-Wno-unused-parameter",
    ],
    header_libs: [
        "libboost_headers",
    ],
    shared: {
        shared_libs: [
            "libboost_system",
        ],
    },
    srcs : [
        "filesystem/src/**/*.cpp",
    ],
    export_include_dirs: ["filesystem/include"],
    export_header_lib_headers: [
        "libboost_headers",
    ],
}
cc_library {
    name: "libboost_log",
    defaults: ["boost_library_defaults"],
    //FIXME: build workaround
    cflags: [
        "-Wno-implicit-fallthrough",
        "-Wno-non-virtual-dtor",
        "-Wno-unused-parameter",
    ],
    header_libs: [
        "libboost_headers",
    ],
    shared: {
        shared_libs: [
            "libboost_thread",
            "libboost_filesystem",
            "libboost_regex",
            "libboost_system",
        ],
    },
    srcs : [
        "log/src/**/*.cpp",
    ],
    exclude_srcs : [
        "log/src/dump_ssse3.cpp",
        "log/src/dump_avx2.cpp",
        "log/src/windows/*.cpp"
    ],
    local_include_dirs : [
        "log/src",
        "log/src/posix",
        "log/src/setup",
        "log/src/windows",
    ],
    export_include_dirs: ["log/include"],
    export_header_lib_headers: [
        "libboost_headers",
    ],
}
cc_library {
    name: "libboost_program_options",
    defaults: ["boost_library_defaults"],
    header_libs: [
        "libboost_headers",
    ],
    srcs : [
        "program_options/src/**/*.cpp",
    ],
    export_include_dirs: ["program_options/include"],
    export_header_lib_headers: [
        "libboost_headers",
    ],
}
cc_library {
    name: "libboost_regex",
    defaults: ["boost_library_defaults"],
    //FIXME: build workaround
    cflags: [
        "-Wno-implicit-fallthrough",
    ],
    header_libs: [
        "libboost_headers",
    ],
    srcs : [
        "regex/src/**/*.cpp",
    ],
    export_include_dirs: ["regex/include"],
    export_header_lib_headers: [
        "libboost_headers",
    ],
}
cc_library {
    name: "libboost_system",
    defaults: ["boost_library_defaults"],
    header_libs: [
        "libboost_headers",
    ],
    srcs : [
        "system/src/**/*.cpp",
    ],
    export_include_dirs: ["system/include"],
    export_header_lib_headers: [
        "libboost_headers",
    ],
}
cc_library {
    name: "libboost_thread",
    defaults: ["boost_library_defaults"],
    //FIXME: build workaround
    cflags: [
        "-Wno-non-virtual-dtor",
    ],
    header_libs: [
        "libboost_headers",
    ],
    shared: {
        shared_libs: [
            "libboost_system",
        ],
    },
    srcs : [
        "thread/src/**/*.cpp",
    ],
    exclude_srcs : [
        "thread/src/win32/*.cpp",
        "thread/src/pthread/once_atomic.cpp",
    ],
    local_include_dirs : [
        "thread/src",
        "thread/src/pthread",
    ],
    export_include_dirs: ["thread/include"],
    export_header_lib_headers: [
        "libboost_headers",
    ],
}
