### ISSUE TITLE
routingmanagerd seems to block to subscribe for a eventgroup

### ISSUE THREAD

**Issue by brenkem** [COVESA/vsomeip#285]
When I try the "subscribe-sample.cpp" example of the repository I noticed a difference between the usage of the example directly as routing part and the usage of the routingmanagerd.

- When I run the example directly on the network wireshark shows "Type: 0x06 (Subscribe Eventgroup)".
- But when I run the example behind a running routingmanagerd there is no subscribe on the network.

Does anybody see the same behavior? Do we need to add some functions to the routingmanagerd or is there a more advanced version of the routingmanagerd available?

Best regards.

**Comment by fcmonteiro** [comment]
Hi,
Can you provide us some logs, it seems the service in not configured in routingmanagerd config file, and is internal only.
