### ISSUE TITLE
Can vsomeip run on different network segment IP addresses？

### ISSUE THREAD

**Issue by ziyangfu** [COVESA/vsomeip#286]
II am tring to run service and client on different network segment like this:
service:
IP:192.168.90.50 netmask:255.255.255.0
client:
IP:192.168.100.60 netmask:255.255.255.0
I used a router for multicast forwarding, however, the communication was not successful.

**Comment by ByteXiaoTang** [comment]
Not in the  LAN.

**Comment by journey175** [comment]
you have to config the serviceid、instanceid、methodid in the routermanagerd`s vsomeip.json.
