### ISSUE TITLE
Compatible versions for building vsomeip with CommonAPIs

### ISSUE THREAD

**Issue by masongk** [COVESA/vsomeip#287]
Hello All,

I am trying to build vsomeip, CommonAPI-core-runtime, CommonAPI-someip-runtime along with generators for CommonAPI -core  and CommonAPI-someip-generator

Can you let me know the compatible version for building or the document to refer to while building the application!

**Comment by goncaloalmeida** [comment]
Closing ticket: Ticket already answered.

> I have tested the following versions： capicxx-core-runtime v3.2.0 capicxx-someip-runtime v3.2.0 commonapi_core_generator v3.2.0.1 commonapi_someip_generator v3.2.0.1 vsomeip 3.1.20.3
