### ISSUE TITLE
How can I not use UNIX domain socket.

### ISSUE THREAD

**Issue by acodercat** [COVESA/vsomeip#290]
Because I want to use tcpdump to capture vsomeip message. 
I can't use tcpdump to capture vsomeip message in UNIX domain socket.

**Comment by zmurf** [comment]
Yes. I would also like to know if it is possible to disable UDS and communicate over TCP even on local services.

**Comment by zhangslice** [comment]
Have you solved your problem?  I have the same problem, any good advice

**Comment by lutzbichler** [comment]
The internal communication always uses Unix domain sockets on Linux and TCP on Windows. It is not possible to change this without changing the code.

**Comment by zmurf** [comment]
I solved it by running one of the applications in a docker container with bridged network. But that is often very cumbersome.

I also tried solving it by changing the vsomeip code, and it works... But that is not really a viable solution. We have no wish to add that kind of maintenance to our project.

**Comment by goncaloalmeida** [comment]
Closing ticket: Ticket has already been answered, please check the answer:

> The internal communication always uses Unix domain sockets on Linux and TCP on Windows. It is not possible to change this without changing the code.
