### ISSUE TITLE
Why the client config requires the `service-discovery` section?

### ISSUE THREAD

**Issue by andrasi** [COVESA/vsomeip#292]
As far as I can understand the `service-discovery` section of the configuration contains items which are relevant for the service side only and not the client.

Why this is also needed on the client side?

Thank you!

**Comment by lutzbichler** [comment]
There parts of the service-discovery section (especially the multicast address) that is needed on client and server side.

**Comment by ByteXiaoTang** [comment]
someip services have two stages. Firstly, service discovery. Service and client both have sd, so that they can start at different time.
