### ISSUE TITLE
Missing default values for the configuration paramters

### ISSUE THREAD

**Issue by andrasi** [COVESA/vsomeip#293]
Hello,

There are configuration items which have no default value specified, for example:  `tcp-restart-aborts-max`
Also, there's a mention of these files: `vsomeip_std.json, vsomeip_app.json and vsomeip_plc.json` which I can't seem to be able to find.

**Comment by sisco0** [comment]
After my research, the default value for `tcp-restart-aborts-max` is specified at 5. I paste the related references below:

https://github.com/COVESA/vsomeip/blob/13f9c89ced6ffaeb1faf485152e27e1f40d234cd/implementation/configuration/src/configuration_impl.cpp#L84
https://github.com/COVESA/vsomeip/blob/13f9c89ced6ffaeb1faf485152e27e1f40d234cd/implementation/configuration/include/internal.hpp.in#L70

Where is the failing point for this default value, or where would you like it to be predefined?

Secondly, the files that you mention are part of the `VSOMEIP_MANDATORY_CONFIGURATION_FILES` default definition, which are optionally specified. 
https://github.com/COVESA/vsomeip/blob/13f9c89ced6ffaeb1faf485152e27e1f40d234cd/implementation/configuration/include/internal.hpp.in#L23
The description for this constant purpose is found below, and another issue about its purpose is related https://github.com/COVESA/vsomeip/issues/243
https://github.com/COVESA/vsomeip/blob/13f9c89ced6ffaeb1faf485152e27e1f40d234cd/documentation/vsomeipUserGuide#L275-L279
