### ISSUE TITLE
Error : Missing files for android build.

### ISSUE THREAD

**Issue by RohitIti88** [COVESA/vsomeip#295]
Error : 
vsomeip/implementation/helper/1.70/boost/asio/basic_socket_ext_local.hpp:22:10: fatal error: 'boost/asio/detail/io_object_impl.hpp' file not found
#include <boost/asio/detail/io_object_impl.hpp>

io_object_impl.hpp and some other files are missing from the folder. Lot of compilation errors. 
mm command always fails to build for android

**Comment by nkh-lab** [comment]
Do you have Boost on your AOSP tree? If no here is example how to apply it https://github.com/nkh-lab/aosp-boost.

**Comment by RohitIti88** [comment]
Hello COVESA/vsomeip,
Yes I have followed this step and boost is also available in aosp tree.

Cmake .. and make works but mma dosent.

Thanks and regards,
  Rohit iti

**Comment by RohitIti88** [comment]
Hello  Nikolay,
Thank you . I followed this step and initially it didnt work. this is because ofthe issue at my AOSP tree.
Thank you for highlighting . It works fine now.

**Comment by ByteXiaoTang** [comment]
Sometimes you may compilie under aach64,  cross compilier. You should build boost first

**Comment by RohitIti88** [comment]
issue was with local AOSP tree.
