### ISSUE TITLE
What is the meaning of "its" ?

### ISSUE THREAD

**Issue by pkadams** [COVESA/vsomeip#296]
I see its_xxx all over the code. 
For example:
`auto its_connection = connection_matrix_.find(r.first);`

What does its stand for? Perhaps it means instance?

**Comment by ByteXiaoTang** [comment]
Just the connection object

**Comment by lutzbichler** [comment]
There is no special meaning, it is just a naming convention: Local variables within the vsomeip-lib code are prefixed with "its_", arguments with "_" and member variables are postfixed with "_".
