### ISSUE TITLE
wrong compiler option given -g if not build with MSVC

### ISSUE THREAD

**Issue by xuantambk** [COVESA/vsomeip#298]
![image](https://user-images.githubusercontent.com/27656811/144752061-8fb7304e-d7f8-464f-8211-9d4f6f38e387.png)

If not built with MSVC you will alwasy build with -g in CMAKE_CXX_FLAGS
    Example when setup build with -DCMAKE_BUILD_TYPE =Release but
    Size of lib someip is about 40MB

**Comment by ByteXiaoTang** [comment]
You shou modify the cmake and delete some compilier params which represent the debug info
