### ISSUE TITLE
How to port someIP into your own project (without running the system)

### ISSUE THREAD

**Issue by zhangslice** [COVESA/vsomeip#299]
Hi，
          How to port someIP into your own project (without running the system), do you have any documentation that describes what needs to be modified

**Comment by ByteXiaoTang** [comment]
是指没有system模块吗？那就修改cmake就好了

**Comment by zhangslice** [comment]
奥，不是的，因为我打算在单片机上裸机跑。

**Comment by goncaloalmeida** [comment]
We don't have any kind of documentation for this type of usage.
