### ISSUE TITLE
E2E: How to configure 'custom profile' to represent E2E Profile 7

### ISSUE THREAD

**Issue by turboaffe** [COVESA/vsomeip#310]
Dear vsomeip maintainers, is it possible to configure a 'custom profile' to be used as profile 7?
Thanks!

**Comment by sgpires** [comment]
Hi @turboaffe , at the moment it is only possible to use profile 1, profile 4 and a custom profile that uses the 32-bit Ethernet CRC, so it is not possible to configure any other profile to be used as profile 7.

**Comment by goncaloalmeida** [comment]
@turboaffe if you want to add this feature feel free to create a PR.

**Comment by GHARBIAchref** [comment]
Hello @goncaloalmeida 
 I want to use end-to-end protection in my application. Is using end-to-end protection done solely through configuration in .json configuration files on both the client and server sides of the services, or does it also require code implementation within my algorithm? And how can I verify if the E2E protection profile 4 is working correctly in Wireshark? 
 thanks
