### ISSUE TITLE
ETS #33 malformed_message reply.

### ISSUE THREAD

**Issue by justoneanotheruser** [COVESA/vsomeip#321]
ETS testcase #33 is:
"Check that the DUT can handle an echoUINT8ArrayMinSize which is shorter 
than 3 elements of the array."
Then expected reply is MALFORMED_MESSAGE

For AUTOSAR xml files specify what it should do for each RequestID (what is the allowed length and the type), but is there a way to do something similar with vsomeip? as the type is not send with payload. So how can I inform ETS that for given RequestID it should reply with error if the payload does not match requirements?

**Comment by Ginakira** [comment]
I think it should be done in the vsomeip application instead of SOME/IP protocol layer.

**Comment by goncaloalmeida** [comment]
yes agreed, this is someip specification, not vsomeip project.
