### ISSUE TITLE
the server reboot, the client will be unsubscribes any event, are there some ways to avoid  the client to unsubscribes?

### ISSUE THREAD

**Issue by fengtuo58** [COVESA/vsomeip#324]

**Comment by fengtuo58** [comment]
the client will have a log : "Reboot detected: IP.  ..." in service_discovery_impl::on_message

**Comment by fengtuo58** [comment]
@mwarning

**Comment by fengtuo58** [comment]
register_reboot_notification_handler  register user handler

**Comment by mwarning** [comment]
I do not understand what this is about..
