### ISSUE TITLE
Can't  download/find vsomeip v2.14.18

### ISSUE THREAD

**Issue by anotherguest** [COVESA/vsomeip#329]
v2.14.18 has been indicated in the CHANGES file as the last version of vsomeip version 2. 
Where can I download v2.14.18 or the related patchset as compared to v2.14.16?
For any one based on vsomeip v2 it would be nice to have the opportunity to apply these patches to the latest released version v2.14.16

**Comment by goncaloalmeida** [comment]
Closing ticket: This version is quite old and is not present specifically on the open-source project.
