### ISSUE TITLE
Using vsomeip with multiple VLANs

### ISSUE THREAD

**Issue by montioo** [COVESA/vsomeip#334]
Hey,
I have a machine that defines multiple VLANs and I am wondering how I can use vsomeip in a setting like this.

From my understanding, a configuration file can only hold one unicast address, but I found that for each _application_ in the config, you can define an _overlay_. And this overlay is basically the path to another configuration file which holds other values for _unicast_, etc. for the VLAN I want a specific application to run on.

This would mean I have on vsomeip runtime. This runtime has one application per VLAN.

Is this correct so far or is there another preferred way to deal with multiple VLANs? Thank you!

**Comment by journey175** [comment]
Yes, overlay config can  redefine the special application with the "network","unicast", "routing"... 
but commonly,  each vlan can only deploy one routing app to transform the message between different network with converting muticast message.

**Comment by fabioazola** [comment]
Hey;
I have two network cards installed on the PC ;
Is it possible to put two application someip working independently on the some network? Ip1=service 1 / ip2=service 2
