### ISSUE TITLE
Can I create two servers on one machine?

### ISSUE THREAD

**Issue by RunningWay** [COVESA/vsomeip#337]
currently,  i try to create two server process on one machine, and they listen on the same unicast and network interface.  after client starting,  the client always received the reboot detect event of the server.   what should i do to support this scene？ tks!

**Comment by journey175** [comment]
Usually, it is not allowed to deploy the two services with the same service and instance, I think。

**Comment by ByteXiaoTang** [comment]
just one will work , until another has showdown , the next work and offer service
