### ISSUE TITLE
Redefinition of local variable causing set to be empty after block 

### ISSUE THREAD

**Issue by sensokame** [COVESA/vsomeip#338]
This line contains redefinition of a local variable inside an if block, this means that after the if block the variable will be empty again, this causes local configuration files to not be taken into consideration.
I believe this line should be removed.

https://github.com/COVESA/vsomeip/blob/17cc55f24d1c56f6a5dcca6065a227ca91d01c90/implementation/configuration/src/configuration_impl.cpp#L239

**Comment by goncaloalmeida** [comment]
Original PR closed -> project does not compile.
