### ISSUE TITLE
Can I create One Server and One Client with 2 different Applications？

### ISSUE THREAD

**Issue by Zhang8912** [COVESA/vsomeip#341]
Hello, Everyone. I am trying to create one Server in first Linux and one Client with 2 different Applications(but apps must have same clientID) in second Linux via udp.jason.
1. Is possible to build this system?
2. If yes, how can I do this?

**Comment by lutzbichler** [comment]
Two applications need to have different client identifiers (as they are also the application identifiers).

**Comment by ByteXiaoTang** [comment]
id should be unique

**Comment by goncaloalmeida** [comment]
Closing ticket: Ticket already answered.
