### ISSUE TITLE
Changing Instance IDs during Runtime

### ISSUE THREAD

**Issue by rschrader** [COVESA/vsomeip#349]
Hi, 

I want to use vsomeip in a product where the end user can combine multiple items of the same product in one ethernet network. This means that all of these items have the same software version and therefore also the same instance ids configured when they are produced. To avoid instance ID conflicts I want to have the possibility to change the instance ID during runtime and without restart the configuration or reloading a modified configuration file. 

I have already a patch for vsomeip to allow dynamic changing of the instance id. Is that something you would consider integrating into the vsomeip mainline?

Thanks,
Raphael

**Comment by DiogoPedrozza** [comment]
The following PR is not accepted and will be closed since most of the same functionalities can already be achieved by using an already existing application::update_service_configuration.
As per our internal discussion it is believe to not be necessary.
