### ISSUE TITLE
SOMEIP Shutdown fails

### ISSUE THREAD

**Issue by sasidhar-ss** [COVESA/vsomeip#354]
Hi, 
I am starting the Someip connection dispatch in a thread. But when i tried to terminate the thread, I see that SOMEIP is not getting terminated and it is still running in the thread. Below is the log. How do i terminate the SOMEIP?

[error] application_impl::shutdown: stopping routing,  catched exception: Invalid argument
 [info] udp_server_endpoint_impl: SO_RCVBUF is: 212992
[info] udp_server_endpoint_impl: SO_RCVBUF (Multicast) is: 212992
 [error] leave_unlocked:set_option: Cannot assign requested address
 [error] udp_server_endpoint_impl::join:set_option: Address already in use
 [info] SOME/IP routing ready.

BR,
Sasidhar

**Comment by ByteXiaoTang** [comment]
kill -9 , some thread will wait for source to be recycled
