### ISSUE TITLE
Install wrong files when enabling the "COM_PAT" in Raspberry Pi.

### ISSUE THREAD

**Issue by WWjsnt10** [COVESA/vsomeip#357]
Hi,
I built the vsomeip 3.1.14.1 with command “cmake -DENABLE_COMPAT=1 ..” -> "make"  -> "sudo make install".

However, the files in the folder "/usr/local/include/vsomeip" are from "interface/vsomeip" not from the "interface/compat/vsomeip".
Because I cannot use the interface "    virtual void offer_event(service_t _service,instance_t _instance, event_t _event const std::set<eventgroup_t> &_eventgroups, bool _is_field) = 0;". 

Please help to check that how to install the files from "interface/compat/vsomeip".

**Comment by fcmonteiro** [comment]
Please retest with the latest vsomeip 3.3.x
Thanks
