### ISSUE TITLE
Help needed in clarification of port type in .json file

### ISSUE THREAD

**Issue by Ravi-Teja-konda** [COVESA/vsomeip#358]
Hello All,

Can we have a both reliable and unreliable for a service which implements both methods and events

For example :

{
                    "service" : "1234",
                    "instance" : "0x12130",
                    "unreliable" : "31337",
                    "reliable" : { "port" : "4590", "enable-magic-cookies" : "false" }
                },
                {
                    "service" : "5678",
                    "instance" : "0x9876",
                     "unreliable" : "31337",
                    "reliable" : { "port" : "4590", "enable-magic-cookies" : "false" }
                }
}

In the above services it uses communication as both reliable and unreliable 
Is the service is open for both TCP and UDP for methods and events ?

Can client the connect to any port like TCP- 31337 and UDP-4590  for one service ?

**Comment by ByteXiaoTang** [comment]
when you sub. you can set sub type

**Comment by zhaoxin39913** [comment]
> 

Of course you can have two ports (TCP and UDP) listening on one service. And both ports are available to connect.  Also you can set the reliability type (TCP or UDP) when calling app->send() to specify it.

**Comment by goncaloalmeida** [comment]
Closing ticket: Ticket already answered.

> > 
> 
> Of course you can have two ports (TCP and UDP) listening on one service. And both ports are available to connect. Also you can set the reliability type (TCP or UDP) when calling app->send() to specify it.
