### ISSUE TITLE
TTL value is wrong in the transmitted message - TTL issue

### ISSUE THREAD

**Issue by Dinakaran1** [COVESA/vsomeip#365]
I have configured TTL value as 3 in the configuration file for the service discovery.
But in real it ends up with different value.
Here I have attached screen shot of the 
[TTL_Analyisis_Result_220606.xlsx](https://github.com/COVESA/vsomeip/files/9199535/TTL_Analyisis_Result_220606.xlsx)
Wireshark capture.
![Wireshark_capture](https://user-images.githubusercontent.com/110098006/181262911-753b1382-d556-47d2-98bb-d30c8d364c8f.png)

**Comment by goncaloalmeida** [comment]
Closing ticket: This is the normal behavior for the find messages. The TTL value is only changed for the OFFER message.
