### ISSUE TITLE
NETLINK is blocked while using vsomeip in android application

### ISSUE THREAD

**Issue by RohitIti88** [COVESA/vsomeip#370]
NETLINK is blocked while using vsomeip in android application . In single phone if we start both service and client then it works but if we try to connect to different device 
then "Error binding NETLINK socket:" is appearing while bind. 
I am trying this on Oneplus6 rooted device with android version 11 and boost 1.7.

In vsomeip\implementation\endpoints\src\netlink_connector.cpp netlink is used and some people are suggesting this needs to be updated to "ifaddrs". 
I also see in MQTT "ifaddrs " is used.

Is there any workaround for this issue?

**Comment by feuillatte** [comment]
This is an issue with your Android environment, not vsomeip. It won't function without netlink in its current state.

**Comment by goncaloalmeida** [comment]
@RohitIti88 Does the problem still occur?

**Comment by goncaloalmeida** [comment]
Closing the ticket -> if the problem still occurs please reopen the ticket.
