### ISSUE TITLE
if deploy MULTI ROUTE, How to find service by client in local machine? 

### ISSUE THREAD

**Issue by journey175** [COVESA/vsomeip#372]
if deploy MULTI ROUTE, and set every application(client/server) act as its route，and the can find other service by multicast group communication,
but How does the client  find service  in local machine? because in the phase of single route, they are connect by unix domain socket by "routingmanagerd"

**Comment by lutzbichler** [comment]
Internally, the find each other by local messages send through the UDS sockets (especially the routing_info command).

**Comment by goncaloalmeida** [comment]
Closing ticket: Ticket already answered.
