### ISSUE TITLE
the declaration of the servicegroup

### ISSUE THREAD

**Issue by Shangwei1024** [COVESA/vsomeip#376]
I find the defination of struct group_ "std::shared_ptr<servicegroup> group_;" in the  implementation/configuration/include/service.hpp.but i cannot find the declaration of the servicegroup.
Can anyone tell me what servicegroup does？

**Comment by ims0** [comment]
vsomeip_v3::cfg::servicegroup is  incomplete type，This servicegroup only has a declaration and no definition, It is used by pointers type in the project, so compilations do not report errors.
