### ISSUE TITLE
how to subscribe to different services using different UDP ports.

### ISSUE THREAD

**Issue by Shangwei1024** [COVESA/vsomeip#380]
My json configuration file is configured with clients, and I want different UDP ports to subscribe to different events, but I only see one SD message in the SD message. There are multiple entries in this message that subscribe to different events. event, but there is only one 'option, and there is only one UDP port number in it; how do I configure to use different port numbers to subscribe to different services. Can you give me an example?

**Comment by yanxiaochun1005** [comment]
@Shangwei1024 vsomeip.json in eventgroups config multicast member can use different port
