### ISSUE TITLE
vsomeip same port subscribe to services of different devices connected

### ISSUE THREAD

**Issue by linuxflavour** [COVESA/vsomeip#384]
In real scenario when we use two different devices (ECU's) with different ip addresses to provide different services using same listening port at IVI client ( running one instance of vsomeip ) . If we want to subscribe to both services using the same port number with below json configuration how we can vsomeip stack handle ? 
version used : vsomeip_3_1_15_1 
{
    "unicast":"192.168.61.1",
    "network":"someip_unsecure_domain_01",
    "logging":
    {
        "level" : "debug",
        "console" : "true",
        "file" : { "enable" : "true", "path" : "/data/vendor/vsomeip-tcu.log"  },
        "dlt" : "true"
    },
    "tracing":
    {
        "sd_enable":"true"
    },

    "applications":
    [
        {
            "name":"Connectivity_InitialSequence",
            "id":"0x3D1E"
        },
        {
            "name":"Connectivity_ModemStatus",
            "id":"0x3D21"
        },
        {
            "name":"Connectivity_xCall",
            "id":"0x3D23"
        },
        {
            "name":"Connectivity_IP_Conf",
            "id":"0x3D24"
        },
        {
            "name":"Connectivity_OTA_ConnecSetup2",
            "id":"0x3D1D"
        },
        {
            "name":"Connectivity_PrivateCall",
            "id":"0x3D25"
        },
        {
            "name":"Connectivity_Geofencing",
            "id":"0x3D26"
        },
        {
            "name":"Connectivity_VPA",
            "id":"0x3D27"
        },
        {
            "name":"Connectivity_Privacy_Mode",
            "id":"0x3D28"
        },
        {
            "name" : "SomeipClientSample",
            "id" : "0x1278"
        },
        {
            "name" : "SomeipServerSample",
            "id" : "0x1279"
        },
        {
            "name" : "SomeipEventFieldTest",
            "id" : "0x1280"
        }
	],

    "services" :
    [
    	{
    	    "service" : "0x1F",
            "instance":"0x1",
            "unreliable":"30501"
    	},
        {
            "service" : "0x1D",
            "instance" : "0x1",
            "reliable":"30501"
        },
        {
            "service" : "0x9000",
            "instance" : "0x0001",
            "reliable" : "30501",
            "events" :
            [
                {
                    "event" : "0x8001",
                    "is_field" : "false",
                    "is_reliable" : "true"
                },
                {
                    "event" : "0x8002",
                    "is_field" : "true",
                    "is_reliable" : "true"
                }
            ],
            "eventgroups" :
            [
                {
                    "eventgroup" : "0x0001",
                    "events" : ["0x8001"]
                },
                {
                    "eventgroup" : "0x0002",
                    "events" : ["0x8002"]
                }
            ]
        }
    ],

	"clients":
	[
    	{
    	    "service" : "0x1E",
            "instance": "0x1",
            "reliable": ["0"]
    	},
    	{
    	    "service" : "0x21",
            "instance": "0x1",
            "reliable": ["0"]
    	},
    	{
    	    "service" : "0x23",
            "instance": "0x1",
            "reliable": ["0"]
    	},
    	{
    	    "service" : "0x24",
            "instance": "0x1",
            "reliable": ["0"]
    	},
    	{
    	    "service" : "0x25",
            "instance": "0x1",
            "reliable": ["0"]
    	},
        {
            "service" : "0x26",
            "instance": "0x1",
            "reliable": ["0"]
        },
        {
            "service" : "0x27",
            "instance":"0x1",
            "reliable": ["0"]
        },
        {
            "service" : "0x28",
            "instance": "0x1",
            "reliable": ["0"]
        },
        {
            "service" : "0x9001",
            "instance" : "0x0001",
            "reliable" : ["0"]
        }
	],

    "routing":"vsomeipd-tcu",
    "service-discovery" :
    {
        "enable" : "true",
        "multicast" : "237.61.0.1",
        "port" : "30490",
        "protocol" : "udp",
        "initial_delay_min" : "10",
        "initial_delay_max" : "50",
        "repetitions_base_delay" : "100",
        "repetitions_max" : "4",
        "ttl" : "3",
        "cyclic_offer_delay" : "2000",
        "request_response_delay" : "20"
    }
}

Below is error - "Cannot find free client port for communication" we observed & looks like vsomeip stack does not handle this use case. Can i get confirmation if this use case is handled in stack ? what is best way to handle this use case ?

    Line 146747: 09-22 15:38:43.548  1581  1587 E vsomeip : Cannot find free client port for communication to service: 30 instance: 1 remote_port: 30501 reliable: 1
    Line 146748: 09-22 15:38:43.548  1581  1587 E vsomeip : Cannot find free client port for communication to service: 33 instance: 1 remote_port: 30501 reliable: 1
    Line 146749: 09-22 15:38:43.548  1581  1587 E vsomeip : Cannot find free client port for communication to service: 35 instance: 1 remote_port: 30501 reliable: 1
    Line 146750: 09-22 15:38:43.549  1581  1587 E vsomeip : Cannot find free client port for communication to service: 36 instance: 1 remote_port: 30501 reliable: 1
    Line 147044: 09-22 15:38:44.048  1581  1583 E vsomeip : Cannot find free client port for communication to service: 37 instance: 1 remote_port: 30501 reliable: 1

**Comment by anaritarodrigues** [comment]
Hello @linuxflavour,
The issue is not observed with the last version available (3.3.8). 
Note that if you define port as 0, the port will be selected by the system. Try another port.
