### ISSUE TITLE
[Bug] JSON Parser can't parse hashmaps correctly

### ISSUE THREAD

**Issue by Joghurt** [COVESA/vsomeip#387]
"configuration_impl.cpp" does not consider that hashmaps do not need to have a fixed order when parsing the configuration JSON file. For e.g. in case "eventgroups" are physically placed before "events" in the map you get errors. Or if "service" or "instance" come after "events" the used value for service or instance is "0".

**Comment by goncaloalmeida** [comment]
@Joghurt do you want to create a PR fo fix that?
