### ISSUE TITLE
Why vsomeip not support e2e-protect on android?

### ISSUE THREAD

**Issue by jinchangrong** [COVESA/vsomeip#391]
Hi, 
I realize that e2e related functions are implemented in “#ifndef ANDROID” compiled macros. Why not enable e2e-protect on android platform? Is there any platform dependent API be invocated?
thanks!

**Comment by goncaloalmeida** [comment]
@jinchangrong  we don't have a specific reason.
Internally we only use it on Linux, but if you want, feel free to create a PR that activates e2e-protect on Android and/or in Windows (with evidence that this builds on Android and Windows).
