### ISSUE TITLE
Configuration module could not be loaded!

### ISSUE THREAD

**Issue by borasaktanber** [COVESA/vsomeip#393]
While trying to run examples, even if I set configurations I am gettıng this error can you help me guys ?

![image](https://user-images.githubusercontent.com/42763805/205643636-1739a586-bdc3-4fe8-a8f7-44dcfe3163f8.png)

**Comment by mohitrao12** [comment]
rm /tmp/vsomeip.lck

try this

**Comment by mohitrao12** [comment]
if you have build your vsomeip for a different architecture  and trying to run on different architecture then you will get this error

**Comment by borasaktanber** [comment]
@mohitrao12 actually I just followed the steps in reade.me file.

**Comment by borasaktanber** [comment]
Yep it worked thank you. But I want to understand that could you please explain what was the problem and how that command solved it ? :D

**Comment by mohitrao12** [comment]
ldconfig is a program that is used to maintain the shared library cache. This cache is typically stored in the file /etc/ld.so.cache and is used by the system to map a shared library name to the location of the corresponding shared library file.
ldconfig is used to create, update and remove symbolic links for the currently shared libraries based on the lib directories present in the /etc/ld.so.conf.
You usually use this if you get errors about some dynamically linked libraries not being found when starting a program although they are actually present on the system.

**Comment by borasaktanber** [comment]
great! thank you again.
