### ISSUE TITLE
compile error while compiling vsomeip in Android R platform

### ISSUE THREAD

**Issue by JunshengShen** [COVESA/vsomeip#395]
It shows error as below. I can't find "vendor.30" in my environment. How can I fix it?

FAILED: out/soong/build.ninja
out/soong/.bootstrap/bin/soong_build -t -l out/.module_paths/Android.bp.list -b out/soong -n out -d out/soong/build.ninja.d -globFile out/soong/.bootstrap/build-globs.ninja -o out/soong/build.ninja Android.bp
Clang SA is not enabled
error: vendor/yfvet/connectivity/vsomeip-3.1.20.3/Android.bp:158:1: failed to find variation "vendor.30" for module "prebuilt_libvsomeip3-sd" needed by "libvsomeip3-sd"
error: vendor/yfvet/connectivity/vsomeip-3.1.20.3/Android.bp:112:1: failed to find variation "vendor.30" for module "prebuilt_libvsomeip3-cfg" needed by "libvsomeip3-cfg"
error: vendor/yfvet/connectivity/vsomeip-3.1.20.3/Android.bp:136:1: failed to find variation "vendor.30" for module "prebuilt_libvsomeip3-e2e" needed by "libvsomeip3-e2e"

**Comment by goncaloalmeida** [comment]
@JunshengShen could you please test this on the last release (3.3.0 - master branch)?
