### ISSUE TITLE
Error "**Couldn't connect to: /tmp/vsomeip-0 (No such file or directory / 2)**" means value for the key (routing) in configuration file vsomeip.json:

### ISSUE THREAD

**Issue by WWjsnt10** [COVESA/vsomeip#396]
Error "**Couldn't connect to: /tmp/vsomeip-0 (No such file or directory / 2)**" means value for the key (routing) in configuration file vsomeip.json:
... 
"routing" : "**app-name**"
...

and. the argument passed to create_application() call in your application are not matching
...
app = vsomeip::runtime::get()->create_application("**app-name**");
...

_Originally posted by @aananthcn in https://github.com/COVESA/vsomeip/issues/43#issuecomment-605846656_
      

I am try to understand that  vsomeip must have one application name = Configured  "routing" name.   I did some tests, modify the json as below:
And Only "routing" : "routingmanagerd" or "hello_world_service" are valid and hello_world can work.   Otherwise, it will report warning "[warning] local_client_endpoint::connect: Couldn't connect to: /tmp/vsomeip-0 (No such file or directory / 2)". 

{
    "unicast":"192.168.139.177",
    "logging":
    {
        "level":"debug",
        "console":"true"
    },

    "applications":
    [
        {
            "name":"hello_world_service",
            "id":"0x4444"
        },
        {
            "name":"hello_world_client",
            "id":"0x5555"
        }
    ],

    "services":
    [
        {
            "service":"0x1111",
            "instance":"0x2222",
            "unreliable":"30509"
        }
    ],
    "routing" : "routingmanagerd" or "hello_world_service" ,or "sample_route",
    "service-discovery" :
    {
        "enable" : "true",
        "multicast" : "224.244.224.245",
        "port" : "30490",
        "protocol" : "udp",
        "initial_delay_min" : "10",
        "initial_delay_max" : "100",
        "repetitions_base_delay" : "200",
        "repetitions_max" : "3",
        "ttl" : "3",
        "cyclic_offer_delay" : "2000",
        "request_response_delay" : "1500"
    }
}

**Am  I  right that we must have one host routing manager in one host?** Otherwise, it can not communicate correctly?

**Comment by yanxiaochun1005** [comment]
host or proxy mode do you want

**Comment by WWjsnt10** [comment]
> host or proxy mode do you want
Actually, I am not very clear about the difference between host and proxy mode(**One new routing Manager???**). 

Also, I just want to send the data by UDP via localhost IP in one host machine.  But it is always using the shared memory to do the communication.

**Comment by yanxiaochun1005** [comment]
if server and client is same ip in one device ,it is will using the shard memory to do the comminication.

**Comment by WWjsnt10** [comment]
> if server and client is same ip in one device ,it is will using the shard memory to do the comminication.

Thanks
