### ISSUE TITLE
aosp error

### ISSUE THREAD

**Issue by daixj** [COVESA/vsomeip#408]
when I port vsomeip in android aosp,and Android.bp add host_supported: true,then
vsomeip/implementation/endpoints/src/netlink_connector.cpp:429:91: error: no member named 'in6_u' in 'in6_addr'
                    const std::uint32_t dst = ntohl((*(struct in6_addr*)RTA_DATA(retrta)).in6_u.u6_addr32[i]);

how can i fix this?

**Comment by fcmonteiro** [comment]
Hi,
Does this issue still occurs with our latest version?
Thanks

cc: @goncaloalmeida
