### ISSUE TITLE
Change Protocol Version and Interface Version

### ISSUE THREAD

**Issue by JBenchi** [COVESA/vsomeip#415]
I'm working with an interface that requires a different Protocol Version and Interface Version.

Is there a way to change these parameters on the header?

![Protocol and Interface Versions](https://user-images.githubusercontent.com/126920238/222838643-40c79769-1a9f-4aa0-b618-99681585fa18.png)

**Comment by lutzbichler** [comment]
The interface version matches the major version that can be set when calling [offer|request]_service. The protocol version cannot be changed at runtime. You can change it by changing the VSOMEIP_PROTOCOL_VERSION define in "interface/vsomeip/defines.hpp", but it does not make sense as vsomeip is implementing version 1 of SOME/IP.
