### ISSUE TITLE
function : load_balancing_option_impl::operator ==, file : Load_balancing_option_impl.cpp

### ISSUE THREAD

**Issue by Jimmy-drod** [COVESA/vsomeip#421]
...
is_equal = (priority_ == its_other.priority_
            && priority_ == its_other.weight_);
...

should it be ?
...
is_equal = (priority_ == its_other.priority_
            && weight_== its_other.weight_);
...

**Comment by goncaloalmeida** [comment]
@Jimmy-drod you are right. Do you want to create a PR with that, or you prefer if we put this fix?
