### ISSUE TITLE
Running Hello world or Custom Applications

### ISSUE THREAD

**Issue by gokulnathps17** [COVESA/vsomeip#431]
Hi I just started working on VSOMEIP and ran into some issues while trying to execute the examples. I was able to successfully build the stack but when trying to run the examples I am getting the message 
"1 configuration module could not be loaded "

I tried to run the application using the command mentioned in the documentation:
VSOMEIP_CONFIGURATION=../helloworld-local.json   VSOMEIP_APPLICATION_NAME=hello_world_service   ./hello_world_service

I also tried out the solution mentioned in https://github.com/COVESA/vsomeip/issues/235#issue-820179318 but this did not resolve my Issue. If anyone can provide some inputs it would be much appreciated.

**Comment by RBEI-ArunKumar** [comment]
Did you build "vsomeip3-cfg" project as well? I also got the similar error and resolved after building this project.

**Comment by gokulnathps17** [comment]
I ran the following commands:
1.  mkdir build
2. cd build
3. cmake ..
4. cd ..
5. make
6. sudo make install

Then I proceed to build the examples and tried executing them all of this is as mentioned in the documentation. How do I build the vsomeip3-cfg? can you please elaborate?

**Comment by gokulnathps17** [comment]
> Did you build "vsomeip3-cfg" project as well? I also got the similar error and resolved after building this project.

I ran the following commands:

mkdir build
cd build
cmake ..
cd ..
make
sudo make install
Then I proceed to build the examples and tried executing them all of this is as mentioned in the documentation. How do I build the vsomeip3-cfg? can you please elaborate?

**Comment by peigao-tw** [comment]
may be you can try to run ``` sudo ldconfig``` to refresh the so cache

**Comment by JoaoMarquues** [comment]
You need to export LD_LIBRARY_PATH="your_build_folder"
cc: @goncaloalmeida

**Comment by gokulnathps17** [comment]
> may be you can try to run ` sudo ldconfig` to refresh the so cache

This does not work for me. Thank you for the response. If you have any other suggestions please let me know.

**Comment by MoraeFox** [comment]
Hello
I'm trying hello_world_service too.
"VSOMEIP_CONFIGURATION" exists on internal.hpp.in but for some reason application_imple.cpp uses "VSOMEIP_CONFIGURATION_MODULE".
The problem for me is, after I try"VSOMEIP_CONFIGURATION_MODULE", there is segmentation fault
Below is gdb output

`k22@k22:~/SOMEIP/vsomeip_1/examples/hello_world/build$ gdb ./hello_world_service 
GNU gdb (Ubuntu 12.1-0ubuntu1~22.04) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./hello_world_service...
(gdb) run
Starting program: /home/k22/SOMEIP/vsomeip_1/examples/hello_world/build/hello_world_service 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff73ff640 (LWP 2676542)]

Thread 1 "hello_world_ser" received signal SIGSEGV, Segmentation fault.
0x00007ffff7db54c5 in vsomeip_v3::application_impl::init (this=0x55555557ee30) at /home/k22/SOMEIP/vsomeip_1/implementation/runtime/src/application_impl.cpp:162
162         if (configuration_->is_local_routing()) {
(gdb) `

**Comment by MoraeFox** [comment]
For me, "sudo ldconfig" fixed both "1 configuration module could not be loaded" issue and Segmentation fault
Thanks community

**Comment by gokulnathps17** [comment]
Hi The issue is not fixed for me still.

**Comment by thusharaponnada** [comment]
Dear @goncaloalmeida @DiogoPedrozza ,
Can you kindly help on resolving this error .
Thank you.

**Comment by thusharaponnada** [comment]
hello @gokulnathps17 Is this issue fixed for you?

**Comment by fcmonteiro** [comment]
Hi @thusharaponnada,
I think we never had this issue internally.

This is how we run the CommonAPI and vSomeIP examples, try to adapt the command

`VSOMEIP_CONFIGURATION=vsomeip-client.json COMMONAPI_CONFIG=commonapi4someip.ini LD_LIBRARY_PATH=../../../install_folder/lib:build build/E01HelloWorldClient`

You can run that in a sh script.

**Comment by thusharaponnada** [comment]
hi @fcmonteiro ,
I tried the suggested method. It is still giving the same error.
Kindly let me know if there are any more prerequisites that i've missed or what might be other reasons(like config file permissions..etc...)
Thank you

**Comment by fcmonteiro** [comment]
So, I downloaded an ubuntu 22.04 image and created a clean VM.
And reproduced the "1 configuration module could not be loaded " issue.

- Created a Project folder, cloned vsomeip and googletest
- set GTEST_ROOT using:
`export GTEST_ROOT="/home/ubuntu/Projects/googletest/`
- Compiled vsomeip using:
`cd /home/ubuntu/Projects/`
`cmake -Bbuild -DCMAKE_INSTALL_PREFIX=install_folder -DENABLE_SIGNAL_HANDLING=1 vsomeip/`
`cmake --build build --parallel 4 --target install examples`

Tried to execute the notify-sample in the build/examples folder and got the error.
![Screenshot from 2023-06-09 16-05-42](https://github.com/COVESA/vsomeip/assets/129758664/86825dac-8b5d-437e-9400-6a1dc607c0a6)

You need to pass the correct path to the library using the "**LD_LIBRARY_PATH**", also you need that "lib:build" at the end.

So, I copied the config folder from "vsomeip/config/" to "build/examples/"
And created the script.
`cd /home/ubuntu/Projects/build/examples/`
`nano start.sh`
`VSOMEIP_CONFIGURATION=./config/vsomeip-local.json VSOMEIP_APPLICATION_NAME=service-sample LD_LIBRARY_PATH=/home/ubuntu/Projects/install_folder/lib:build ./notify-sample`
`chmod +x start.sh`
`start.sh`

And the example started fine.

**Comment by thusharaponnada** [comment]
Thank you! It worked!

**Comment by fcmonteiro** [comment]
Closing the issue.

**Comment by manuunam8888** [comment]
> Hi I just started working on VSOMEIP and ran into some issues while trying to execute the examples. I was able to successfully build the stack but when trying to run the examples I am getting the message "1 configuration module could not be loaded "
> 
> I tried to run the application using the command mentioned in the documentation: VSOMEIP_CONFIGURATION=../helloworld-local.json VSOMEIP_APPLICATION_NAME=hello_world_service ./hello_world_service
> 
> I also tried out the solution mentioned in [#235 (comment)](https://github.com/COVESA/vsomeip/issues/235#issue-820179318) but this did not resolve my Issue. If anyone can provide some inputs it would be much appreciated.

I am facing same issue.....Any idea how can I resolve this issue

**Comment by manuunam8888** [comment]
@gokulnathps17  any idea how u resolved that issue with hello_world_service and hello_world_client thing? I am facing the same issue and still tried all the things. Please suggest any other approach u followed and it worked kind
