### ISSUE TITLE
A separate server service instance shall be used per network interface if a service needs to be offered on multiple network interfaces.

### ISSUE THREAD

**Issue by wonjae-song** [COVESA/vsomeip#436]
according to some/ip SD specification, (https://www.autosar.org/fileadmin/standards/R22-11/FO/AUTOSAR_PRS_SOMEIPServiceDiscoveryProtocol.pdf)
- [PRS_SOMEIPSD_00238] A separate server service instance shall be used per network interface if a service needs to be offered on multiple network interfaces
- [PRS_SOMEIPSD_00239] A separate client service instance shall be used per network interface if a service needs to be configured to be accessed using multiple different network interfaces

could I meet above specifications using vsomeip?

I understood that we need to use seperate routing app if we need to offer a service on multiple network interface (ex> eth0 and eth1).
as I know, we can seperate routing manager using seperate vsomeip configuration file ( configure unicast, network, routing for each routing app)
but is it possible that one application use multiple routing? 
It seems that application communicate with routing manager using /etc/"network"-0 UDS. but a configuration file can hold only one "network".

**Comment by yangqiao95** [comment]
do  you  success  arm-Linux   to   arm-tc397-autosar?

**Comment by goncaloalmeida** [comment]
@wonjae-song In vsomeip userguide you can search for "VSOMEIP_CONFIGURATION_<application>" for a brief explanation.
