### ISSUE TITLE
Security configuration for Communication between 2 remote instances

### ISSUE THREAD

**Issue by randheerrk** [COVESA/vsomeip#439]
Is it possible  to authenticate  communication between two remote clients. if it is possible How should I configure the VSOME/IP configuration with the security section for the same.

I tried adding the security configuration by taking a reference from [example json file](https://github.com/COVESA/vsomeip/blob/master/config/vsomeip-tcp-client-security.json). But it is not working.

**Comment by goncaloalmeida** [comment]
Hello @randheerrk 
the security config is used for internal communication, not external communication. 
If you want external security you can use for example IPSec.
