### ISSUE TITLE
Unable to execute vsomeip notify-subscriber example from the different systems

### ISSUE THREAD

**Issue by udit23231** [COVESA/vsomeip#448]
I am trying to run notify-sample and subscribe-sample application in two different instance in the same network, Here client is not able to recognize the notify service

It works fine when I use the same instance, Is there anything that I need to specify in the configs.

In my configs i have specified the local ip in unicast and in the subscriber-client mentioned the server IPs, rest all the things i keep the defaults

![image](https://github.com/COVESA/vsomeip/assets/133321724/cd9018ae-d2d9-4b7c-bee0-3976cc587f13)

**Comment by udit23231** [comment]
Hi @fcmonteiro , tried with the latest too but get same issue.

**Comment by yangqiao95** [comment]
what  is different  systems  ？   ubuntn  and   android?    do  you  try  linux(arm) -to - TC397(ECU)?

**Comment by udit23231** [comment]
Both having same Linux ubuntu OS

**Comment by yangqiao95** [comment]
> 两者都具有相同的 Linux ubuntu 操作系统

linux  to   ubuntu   ?

**Comment by udit23231** [comment]
ubuntu to ubuntu communication same version

**Comment by udit23231** [comment]
I already added those routes in both the instances but same issue

**Comment by yangqiao95** [comment]
config  files  refer  to   https://github.com/COVESA/vsomeip/issues443    
ubuntu  to  ubuntu   successfully   pass

**Comment by udit23231** [comment]
Don't have access to above URL gives me 404

**Comment by yangqiao95** [comment]
> 无法访问上面的 URL 给我 404

https://github.com/COVESA/vsomeip/issues/443

**Comment by fcmonteiro** [comment]
@udit23231, are you able to see the Offers/Finds using wireshark?
I've just tested it locally and with 2 different machines and it's working fine.

**Comment by udit23231** [comment]
Yes its working fine now locally.  In cloud its failing maybe because multicasting is not supporting there.
