### ISSUE TITLE
arm（soc-linux） to arm（mcu-such as infineon-aurix-TC397）in some/ip ?

### ISSUE THREAD

**Issue by yangqiao95** [COVESA/vsomeip#453]
Do you try arm（soc-linux） to arm（mcu-such as infineon-aurix-TC397）in some/ip ?

**Comment by goncaloalmeida** [comment]
no.

**Comment by yangqiao95** [comment]
why&nbsp; no ? just&nbsp; in arm-to-arm(both&nbsp; Linux)



---Original---
From: "Gonçalo ***@***.***&gt;
Date: Wed, May 24, 2023 00:04 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [COVESA/vsomeip] arm（soc-linux） to arm（mcu-such as infineon-aurix-TC397）in some/ip ? (Issue #453)




 
no.
