### ISSUE TITLE
VSOMEIP Support tags in data serialization

### ISSUE THREAD

**Issue by akhedhir** [COVESA/vsomeip#465]
Hello
I would like to know if the VSOMEIP support extensible Someip communication(tags)
  Any feedback is appreciated

**Comment by reymor** [comment]
Hello @akhedhir, 

As far I know vsomeip does not implement the serialization of data structures! This is covered by the SOME/IP binding of CommonAPI. vsomeip just covers the SOME/IP protocol and the Service Discovery (also in vsomeip3 SOME/IP TP). 

The serialization of data structures is implemented by [commonAPI ](https://github.com/COVESA/capicxx-core-tools). Or it could be implemented by your side.

**Comment by BrunoLSilvaCTW** [comment]
Hi @akhedhir, vsomeip does not support tagging or optional members.
