### ISSUE TITLE
Not able to run Hello_World_Service and Hello_World_Client. Showing error related Configuration module could not be loaded.

### ISSUE THREAD

**Issue by manuunam8888** [COVESA/vsomeip#466]
Hi Everyone,

I have followed this steps as below and facing error like "**1 Configuration module could not be loaded!**" . Please help me resolve this issue.
Commands ran before this:
   **_mkdir build
   cd build/
   cmake ..
   make
   sudo make install
   cd ../examples/hello_world/
   mkdir build
   cd build/
   cmake ..
   make_** 

Error found at:
~/Manohar/vsomeip-master/examples/hello_world/build$ _VSOMEIP_CONFIGURATION=../helloworld-local.json \
> VSOMEIP_APPLICATION_NAME=hello_world_service \
> ./hello_world_service_
**1 Configuration module could not be loaded!**

**Comment by reymor** [comment]
Hi! As fcmonteiro point out, this is related with the path of your libraries. When you compile the libraries you need to install them, this is done with 

`make install`

Your dynamic linker need to be able to find these symbols. You could check that your vsomeip libraries are located by ld using 

`
ldconfig - v | grep vsomeip
`

The output should be something like this: 

![image](https://github.com/COVESA/vsomeip/assets/39070043/8348c014-5411-4964-9b96-7acc40539699)

If the path where the libraries are installed is not added to the dynamic linker, the solution could be added this to 

`
/etc/ld.so.conf.d/ <--- here you create a file with .conf extension which is the path where your libs are installed
`

after you did that, you rebuild the cache of library filename, by running;

`
ldconfig
`

---- The other solution could be just append the path where the libraries are installed to the  ---- 

`
export LD_LIBRARY_PATH=/path/to/vsomeip/libraries
`

 before you run your program. Or by a script as fcmonteiro  said.

**Comment by manuunam8888** [comment]
Thanks it worked

**Comment by goncaloalmeida** [comment]
https://github.com/COVESA/vsomeip/issues/431#issuecomment-1584785650

**Comment by TienVuHong** [comment]
> Hi! As fcmonteiro point out, this is related with the path of your libraries. When you compile the libraries you need to install them, this is done with
> 
> `make install`
> 
> Your dynamic linker need to be able to find these symbols. You could check that your vsomeip libraries are located by ld using
> 
> `ldconfig -v | grep vsomeip`
> 
> The output should be something like this:
> 
> ![image](https://private-user-images.githubusercontent.com/39070043/245784508-8348c014-5411-4964-9b96-7acc40539699.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NDUwNzIsIm5iZiI6MTcxNzc0NDc3MiwicGF0aCI6Ii8zOTA3MDA0My8yNDU3ODQ1MDgtODM0OGMwMTQtNTQxMS00OTY0LTliOTYtN2FjYzQwNTM5Njk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDA3MTkzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyNGUxNTc2OGZmNTA4ZTc4NTMyNzM0YmUyZTFiM2FjODhhMzA0MWM5ZDcyOThkOTFlMzQ0Mzc3Mjc5NGFlYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OUKuaaLi-0980770mSGdfFLIENnwdJGuPXztPS18MnQ)
> 
> If the path where the libraries are installed is not added to the dynamic linker, the solution could be added this to
> 
> `/etc/ld.so.conf.d/ <--- here you create a file with .conf extension which is the path where your libs are installed`
> 
> after you did that, you rebuild the cache of library filename, by running;
> 
> `ldconfig`
> 
> ---- The other solution could be just append the path where the libraries are installed to the ----
> 
> `export LD_LIBRARY_PATH=/path/to/vsomeip/libraries`
> 
> before you run your program. Or by a script as fcmonteiro said.

That help,
Thanks
