### ISSUE TITLE
Signal-Based Header compatibilities

### ISSUE THREAD

**Issue by reymor** [COVESA/vsomeip#467]
I have doubts regarding the use of vsomeip in certain scenarios. Starting from AUTOSAR R21-11, I can see 3 variants of "S2S header" which are: 

- Full SOME/IP header
![varios_diagrams-Full SOME_IP Header drawio](https://github.com/COVESA/vsomeip/assets/39070043/43cb8b45-31b2-4cce-a3e7-55a9fca37db2)

- Signal-Based Header
![varios_diagrams-Signal-Based Header drawio](https://github.com/COVESA/vsomeip/assets/39070043/deedfd89-0117-452c-bbf1-ddc40579dcf1)

- No header
![varios_diagrams-No Header drawio](https://github.com/COVESA/vsomeip/assets/39070043/682d6536-7797-4411-b822-c38cddf87aeb)

Are ways of use vsomeip under these circustances (Signal-Based Header) ?

The Signal-Based header could arise in this use of case (Classic AUTOSAR): 

![varios_diagrams-Use case routing drawio](https://github.com/COVESA/vsomeip/assets/39070043/a57092f5-08fb-42f4-89a3-6da589b360f9)

Thanks in advance!

Ref: [Specification of Manifest](https://www.autosar.org/fileadmin/standards/R21-11/AP/AUTOSAR_TPS_ManifestSpecification.pdf (R21-11)) -->  Page 575 (Section 12.2.1 Message Header

[](url)

**Comment by BrunoLSilvaCTW** [comment]
Hi @reymor, vsomeip only supports the "Full SOME/IP header".
