### ISSUE TITLE
1 Configuration module could not be loaded !

### ISSUE THREAD

**Issue by devashishmishra90** [COVESA/vsomeip#480]
![image](https://github.com/COVESA/vsomeip/assets/47450255/bd4a833d-a2b8-4a9c-8e83-d86884d3b687)

**Comment by goncaloalmeida** [comment]
Please check https://github.com/COVESA/vsomeip/issues/468

**Comment by devashishmishra90** [comment]
**i cloned vsomeip into home directory then,**
mkdir build
cd build
cmake ..
make
make install

**after that i go to** 
vsomeip/examples/helloworld
mkdir build
cd build
cmake ..
make

& **RUN THIS**
VSOMEIP_CONFIGURATION=../helloworld-local.json \
VSOMEIP_APPLICATION_NAME=hello_world_service \
./hello_world_service

still getting the problem after looking into #466

**Comment by goncaloalmeida** [comment]
https://github.com/COVESA/vsomeip/issues/431#issuecomment-1584785650

**Comment by devashishmishra90** [comment]
Hey mate, I also did whatever was mentioned in #431 but still the issue is there

**Comment by hmluqman** [comment]
In my case, LD_LIBRARY_PATH was missing in my Linux host system. It was first time I was compiling C++.
