### ISSUE TITLE
I want to send different data types over vsomeip? 

### ISSUE THREAD

**Issue by ArslanMunaim** [COVESA/vsomeip#490]
Hello, I want to send different data types and data structures over vsomeip in one packet, for-example boolean, int, float, integer and float arrays. Does anybody has any example how can i send it with in one message?

**Comment by reymor** [comment]
Hello @ArslanMunaim,

As far I know vsomeip does not implement the serialization of data structures! This is covered by the SOME/IP binding of CommonAPI. vsomeip just covers the SOME/IP protocol and the Service Discovery (also in vsomeip3 SOME/IP TP).

The serialization of data structures is implemented by [commonAPI ](https://github.com/COVESA/capicxx-core-tools). Or it could be implemented by your side.

One use of case which I would not recommend without using a library that do this for you or kind of way of make scalable system. You need a serializer in your server side and deserializer in your client side. 

For instance, imagine that you want to send this struct: 

```cpp
typedef struct {
   uint32_t a;
   uint16_t b;
   uint8_t c;
} data_t;
```

In your sender side, you could have something like this:

```cpp
{
#define BUFFER_SIZE 7U
  /* data  is an instance of data_t and you fill in certain part of your app or 
       you call this function with it 
  */ 
  uint8_t buffer[BUFFER_SIZE];
  uint32_t index = 0;
  std::shared_ptr<vsomeip::payload> payload_;
  payload_ = vsomeip::runtime::get()->create_payload();

  *((uint32_t*)&(buffer[index])) = data.a;
  index+=4;
  *((uint16_t*)&(buffer[index])) = data.b;
  index+=2;
  *((uint16_t*)&(buffer[index])) = data.c;
  index+=1;

  payload_->set_data(buffer, index);
  app_->notify(service_id, instance, event_id payload_);
}

```

In your receiver side you must have something like this:

```cpp
  /* data is an instance of data_t
  */  
  uint8_t *buffer_ptr = _data->get_payload()->get_data();
  uint32_t buffer_len = _data->get_payload()->get_length();
  uint32  index = 0;
  
  data.a = *((uint32_t*)&(buffer_ptr[index]));
  index += 4;
  data.b = *((uint16_t*)&(buffer_ptr[index]));
  index += 2;
  data.c = *((uint8_t*)&(buffer_ptr[index]));
  index += 1;
```

You could explore more information here: [SOME/IP ](https://some-ip.com/details.shtml). Also in [AUTOSAR specs](https://www.autosar.org/fileadmin/standards/R1-0/FO/AUTOSAR_PRS_SOMEIPProtocol.pdf) section 4.1.4.2

As I said this is just a dummy example on how you could do it.
