### ISSUE TITLE
SomeIP : Server sends "NACK subscribe eventgroup" even after client sent the subscribe eventgroup

### ISSUE THREAD

**Issue by malatesh-design** [COVESA/vsomeip#496]
NACK subscribe eventgroup is sent from the server(Simulated in CANoe) even after "subcribe Eventgroup" sent from the client(Real ECU).
Server --> offers to all --> OK
Client --> sent "subscribe eventgroup"--> OK
Server --> sent "NACK subscribe eventgroup" --> NOK
Do you know what might be the issue why we received NACK subscribe eventgroup from Server even the offers are subscribed by client.

**Comment by reymor** [comment]
Hello @malatesh-design 

Use wireshark for debugging and check why is NACK subscribe eventgroup. 

It is difficult to say without a trace of your communication. I will say that check that interface versions match. There is a disector in newer versions of wireshark that could help you.

**Comment by govarthananram96** [comment]
Hello @malatesh-design 
As first step, You can check if Major and Minor version of offer and request service are same.

**Comment by fcmonteiro** [comment]
Hello,
Can you provide us more logs or if possible some examples to replicate the issue.
Thanks

**Comment by fcmonteiro** [comment]
Please provide pcap files of the issue
