### ISSUE TITLE
Documentation: service-example.cpp with outdated parameterization

### ISSUE THREAD

**Issue by nachtfuchs** [COVESA/vsomeip#501]
https://github.com/COVESA/vsomeip/wiki/vsomeip-in-10-minutes#request--response

the service-example.cpp has an outdated command "app->send(its_response, true);". Solution is:  "app->send(its_response);"

**Comment by goncaloalmeida** [comment]
@nachtfuchs please create a PR with the change if you want :)

**Comment by nachtfuchs** [comment]
Hi Goncalo,

I tried to, but could not figure out how to make the pull request for the
wiki. I researched and thought that pull-requests to wikis are not
possible. Which made sense in my understanding of the wiki.
If I am wrong, please let me know. Then I will try to find a way to
celebrate the pull-request.


Best

nachtfuchs



Gonçalo Almeida ***@***.***> schrieb am Fr., 1. Sept. 2023,
11:22:

**Comment by goncaloalmeida** [comment]
@nachtfuchs right, we will do it. thanks!

**Comment by goncaloalmeida** [comment]
Edition done.
