### ISSUE TITLE
V3.3.8, there is a typo issue in the "../implementation/endpoints/src/server_endpoint_impl.cpp"

### ISSUE THREAD

**Issue by biggoldenbee** [COVESA/vsomeip#508]
V3.3.8, there is a typo issue in the "../implementation/endpoints/src/server_endpoint_impl.cpp", about line 841 as below:

// Instantiate template
#ifdef __linux__
template class server_endpoint_impl<boost::asio::local::stream_protocol>;
#if VSOMEIP_BOOST_VERSION < 106600
template class server_endpoint_impl<boost::asio::local::stream_protocol_ext>;
#endif  
#endif

the correct code should to be modified as below:

// Instantiate template
#ifdef __linux__
#if VSOMEIP_BOOST_VERSION >= 106600
template class server_endpoint_impl<boost::asio::local::stream_protocol>;
#else
template class server_endpoint_impl<boost::asio::local::stream_protocol_ext>;
#endif
#endif

since if you use boost_1650 to compile you will meet following error info:
<img width="1228" alt="Screen Shot 2023-08-19 at 20 08 24" src="https://github.com/COVESA/vsomeip/assets/19463589/6c851918-f45e-47ac-8892-73f0de090087">

**Comment by fcmonteiro** [comment]
We a fix for this already internally, should be available in the next version of vsomeip.
