### ISSUE TITLE
osx support

### ISSUE THREAD

**Issue by HerrCai0907** [COVESA/vsomeip#514]
Now VSOMEIP doesn't support build in OSX.
Is there any technical block point to build and run in OSX or is it just not in plan?

If it is due to no plan / capacity, will maintainer accept the patch for OSX supporting?

**Comment by goncaloalmeida** [comment]
@HerrCai0907 we don't provide support for OSX, only linux, and windows, however, we accept any patch that is good for the project such as supporting OSX.
