### ISSUE TITLE
Can't see Using configuration file: "/home/path/to/config/vsomeip.json" line

### ISSUE THREAD

**Issue by lbilal0016** [COVESA/vsomeip#518]
I cannot load the .json configuration files in vsomeip3. I have tried adding the cmake flag -DDEFAULT_CONFIGURATION_FILE=, tried placing the .json in the same folder with the executables, nothing helped so far. 
Another problem is, I don't see a file /etc/vsomeip, or /etc/vsomeip3 for that matter. Have anyone had this issue before?

**Comment by fcmonteiro** [comment]
Hello,
You can use the VSOMEIP_CONFIGURATION flag when calling the application

Eg: 
`VSOMEIP_CONFIGURATION=./config/vsomeip-local.json VSOMEIP_APPLICATION_NAME=service-sample LD_LIBRARY_PATH=/home/ubuntu/Projects/install_folder/lib:build ./notify-sample`
