### ISSUE TITLE
If the machine providing the service is directly powered off, then Vsomip's is_available() detection will still not be detected

### ISSUE THREAD

**Issue by superfufufuf** [COVESA/vsomeip#546]
I have two hosts, one running the server and one running the client. When the server is powered off directly. Vsomip can only detect the sd service timeout, and proxy's is_available() return value in commonapi is still true.
We registered a tcp event where a direct server outage would cause the client tcp socket to remain. isAvailable() then returns true all the time, when the server has actually gone offline.

**Comment by duartenfonseca** [comment]
@superfufufuf  Can you send logs or how can we reproduce this problem?
