### ISSUE TITLE
Availability of code for Fire and Forget mechanism without service discovery

### ISSUE THREAD

**Issue by jennyj1** [COVESA/vsomeip#547]
Hi Community,

I was working with SOME/IP and have the need to implement the fire and forget mechanism without service discovery. From the SOMEIP documentation there is very less information regarding how to implement it. 

Does anyone have any code or knowledge on how to implement fire and forget mechanism without service discovery?

It would be of great help if you could share whatever you know about it...

**Comment by goncaloalmeida** [comment]
Hello,
please use the discuss tabs for non-issues. Thanks!
