### ISSUE TITLE
Helloworld.json doesn't work

### ISSUE THREAD

**Issue by coderjingluo** [COVESA/vsomeip#548]
![image](https://github.com/COVESA/vsomeip/assets/35733451/95cd326d-4110-421d-bc02-2b30cf34ef57)
Although I copied the configuration file to the helloworld directory and ran the sh script, the json file doesn't seem to work

**Comment by coderjingluo** [comment]
Also, why can't I catch any traffic about vsomeip using wireshark

**Comment by fcmonteiro** [comment]
Hi @coderjingluo,
As you are starting the example using a script with multiple lines, you need to use a backslash at the end of each line.
Something like this,
![vsomeip_init](https://github.com/COVESA/vsomeip/assets/129758664/30645c71-9d33-49ee-a71c-e515b5dbb11a)
[Some documentation.](https://www.tutorialspoint.com/running-multi-line-shell-code-at-once-from-single-prompt)

Also, if you are running client and the server on the same machine, this use internal communication using UDS and you will not see the traffic in wireshark.
Thanks
