### ISSUE TITLE
package not found via tcpdump

### ISSUE THREAD

**Issue by 123130** [COVESA/vsomeip#552]
I have run the example(hello_world, subscribe/notify and request/response) correctly, but I did not catch any packets via the command(sudo tcpdump -i lo -w someip.pcap).
Anybody know where the problem is?
request:
![image](https://github.com/COVESA/vsomeip/assets/58681779/2604014c-1981-44a6-ba91-195a874ba541)
response:
![image](https://github.com/COVESA/vsomeip/assets/58681779/689d6168-eca9-44c9-bb1a-861f9893296c)
![image](https://github.com/COVESA/vsomeip/assets/58681779/8feae010-d3bc-4dde-b4be-571f101d46e1)

**Comment by dprogm** [comment]
If you are running the client and server locally on your machine you won't see any network traffic because SomeIP is using Unix Domain Sockets for IPC which utilizes kernel buffer memory for data exchange.

**Comment by 123130** [comment]
@dprogm Dear you, thanks a lot for replying my issue.
So, can I use Peach fuzzer to test notify-sample locally on my machine?

**Comment by dprogm** [comment]
The question is what you are trying to achieve? There are methods for sniffing on Unix Domain Sockets, e.g. by using tracepoints or kernel probes and dumping the data. Some months ago I stumbled over [sockdump](https://github.com/mechpen/sockdump), but this requires some extra work. I have asked about it here: https://github.com/mechpen/sockdump/issues/21 

I guess Peach Fuzzer is for Fuzz-Testing. This might be another  topic.

**Comment by 123130** [comment]
@dprogm Thanks a lot!
I also want to capture the traffic of someip, and have seen https://github.com/mechpen/sockdump/issues/21.
Would you like to share the dummy.lua?
Thanks.

**Comment by Avinash19999** [comment]
@123130 Hi, If you are running the server and client applications in a single machine then you will only find the Someip-SD
message when you try to sniff it. When you run the server and client application between two machines or VM's then you can capture the Someip frames.
