### ISSUE TITLE
Feasibility of notification meachnism in subscribe-notify services

### ISSUE THREAD

**Issue by 12falcon** [COVESA/vsomeip#555]
Hello Team,
Is it possible to notify other service just after app_->init() and before app_->start() functionality using 
app_->notify(SAMPLE_SERVICE_ID, SAMPLE_INSTANCE_ID,SAMPLE_EVENT_ID, payload_);

Thank you.
Best regards,
falcon

**Comment by fcmonteiro** [comment]
@12falcon What are you trying to archive?
Have you tested it?

**Comment by lutzbichler** [comment]
Before calling app_-start, the vsomeip io threads are not running. Thus, no message can be sent or received. The only thing that can/will be achieved by calling notify before calling app_->start is the initialization of SOME/IP fields.

**Comment by duartenfonseca** [comment]
since no response for some time, will close the issue
