### ISSUE TITLE
vsomeip: How can i use it?

### ISSUE THREAD

**Issue by jsb9945** [COVESA/vsomeip#562]
I created an image by putting in the vomeip recipe and building it into yocto.
Below is the result of booting the image to find vomeip.

![image](https://github.com/COVESA/vsomeip/assets/87635576/5bd3fff6-d314-4454-b4f3-1b037823f400)

But I don't know how to use this
Can you help me?
Thanks

**Comment by goncaloalmeida** [comment]
Hello, this is not an issue, please use the Discussions tab.
btw, in principle, you can now run some examples in your image.
