### ISSUE TITLE
How to fix the issue: "1 Configuration module could not be loaded!"?

### ISSUE THREAD

**Issue by wangjingxiaomidou** [COVESA/vsomeip#568]
I use the tag 3.3.8 of the code base. And I build and install vsomeip using the method below:
mkdir build
cd build
cmake ..
make
make install

When I build vsomeip3lib, and go to build and run the hello world, I meet the issue, how to fix it?
<img width="938" alt="image" src="https://github.com/COVESA/vsomeip/assets/58726252/e8575e16-97b7-41d6-bad2-eba401e93957">
I use "ldconfig", it still fails.
<img width="910" alt="image" src="https://github.com/COVESA/vsomeip/assets/58726252/f8ea40ad-6340-42fa-a313-a1fd35403bb0">

**Comment by goncaloalmeida** [comment]
https://github.com/COVESA/vsomeip/issues/481#issuecomment-1607168854 :)

**Comment by wangjingxiaomidou** [comment]
@goncaloalmeida ：Hi, I use "ldd /usr/local/lib/libvsomeip3-cfg.so" shows as bwlow, but it still not works.
root@uu1:/media/psf/share/vsomeip-3.3.8/examples/hello_world/build# ldd /usr/local/lib/libvsomeip3-cfg.so
	linux-vdso.so.1 (0x0000ffffb0ec3000)
	libvsomeip3.so.3 => /usr/local/lib/libvsomeip3.so.3 (0x0000ffffb0b80000)
	libboost_filesystem.so.1.74.0 => /lib/aarch64-linux-gnu/libboost_filesystem.so.1.74.0 (0x0000ffffb0b30000)
	libstdc++.so.6 => /lib/aarch64-linux-gnu/libstdc++.so.6 (0x0000ffffb0900000)
	libgcc_s.so.1 => /lib/aarch64-linux-gnu/libgcc_s.so.1 (0x0000ffffb08d0000)
	libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000ffffb0720000)
	/lib/ld-linux-aarch64.so.1 (0x0000ffffb0e8a000)
	libboost_thread.so.1.74.0 => /lib/aarch64-linux-gnu/libboost_thread.so.1.74.0 (0x0000ffffb06e0000)
	libm.so.6 => /lib/aarch64-linux-gnu/libm.so.6 (0x0000ffffb0640000)
<img width="1059" alt="image" src="https://github.com/COVESA/vsomeip/assets/58726252/562c62ff-07fc-4395-95a0-40ed79cb5019">
