### ISSUE TITLE
~/vsomeip/examples/hello_world$ VSOMEIP_CONFIGURATION=./helloworld-local.json VSOMEIP_APPLICATION_NAME=hello_world_service ./hello_world_service  1 Configuration module could not be loaded!

### ISSUE THREAD

**Issue by Hithesh0899** [COVESA/vsomeip#569]
I tried all of my ways to run this but not able to run, kindly help me asap possible because it is very important for me. 
I have give chmod+x even though it is the same , also i have did all the resolutions previously mentioned on this issues portal, but none of them didnt resolve the issue, kindly please resolve.

Thanks and regards,
Hithesh

**Comment by wangjingxiaomidou** [comment]
I also meet the issue.

**Comment by Hithesh0899** [comment]
Seems so strange even if all dependencies are present, it is not getting executed..

**Comment by wangjingxiaomidou** [comment]
Yes, what version of vsomeip do you use?

**Comment by Hithesh0899** [comment]
I am using 3.4.9 the latest version

**Comment by wangjingxiaomidou** [comment]
@Hithesh0899 Do you try the solutions mentioned in https://github.com/COVESA/vsomeip/issues/568?

**Comment by Hithesh0899** [comment]
Yess i have did it ane also Few more resolutions I have tried

**Comment by goncaloalmeida** [comment]
where are declared the VSOMEIP_CONFIGURATION, VSOMEIP_APPLICATION_NAME and LD_LIBRARY_PATH?

**Comment by wangjingxiaomidou** [comment]
@goncaloalmeida How to check? Actually, I use the default parameters. I follow the step:
mkdir build
cd build
cmake ..
make
make install

After install, the installation path is /usr/local/lib
<img width="1234" alt="image" src="https://github.com/COVESA/vsomeip/assets/58726252/16efe139-2bde-4fff-9d96-e079e91b03a7">
wj@uu1:/usr/local/lib$ echo $VSOMEIP_CONFIGURATION
wj@uu1:/usr/local/lib$ echo $VSOMEIP_APPLICATION_NAME
wj@uu1:/usr/local/lib$ echo $LD_LIBRARY_PATH
:/usr/local/lib

**Comment by Hithesh0899** [comment]
> where are declared the VSOMEIP_CONFIGURATION, VSOMEIP_APPLICATION_NAME and LD_LIBRARY_PATH?

yeah how to check, and why we have to use VSOMEIP_CONFIGURATION, VSOMEIP_APPLICATION_NAME , why cant we run the application ./hello_world_service ? this issue is so frequent.. kindly give a proper resolution step on the documentation, it will be so helpful

**Comment by wangjingxiaomidou** [comment]
Sorry, I don't understand. I do not use the VSOMEIP_CONFIGURATION, VSOMEIP_APPLICATION_NAME. When I run /hello_world_service , it show as below:
/media/psf/share/vsomeip-3.3.8/examples/hello_world/build$ ./hello_world_service 
1 Configuration module could not be loaded!

I follow the doc here https://github.com/COVESA/vsomeip, Is it right?

**Comment by goncaloalmeida** [comment]
@wangjingxiaomidou you need to read the readme files, and all the steps indicated in the comments.
https://github.com/COVESA/vsomeip/blob/70d59edc01c9978ada66615c033e941e40561bb6/examples/hello_world/readme

**Comment by wangjingxiaomidou** [comment]
@goncaloalmeida understand, Actually, I have run with the readme resolution, the issue is still exit. Please see the result below:
wj@uu1:/media/psf/share/vsomeip-3.3.8/examples/hello_world/build$ VSOMEIP_CONFIGURATION=../helloworld-local.json \
VSOMEIP_APPLICATION_NAME=hello_world_service \
./hello_world_service
1 Configuration module could not be loaded!
<img width="1065" alt="image" src="https://github.com/COVESA/vsomeip/assets/58726252/4c9968da-e574-4342-8220-f8de9d24fb56">

**Comment by wangjingxiaomidou** [comment]
My infomation
wj@uu1:/media/psf/share/vsomeip-3.3.8/examples/hello_world/build$ ldd /usr/local/lib/libvsomeip3-cfg.so
	linux-vdso.so.1 (0x0000ffff80661000)
	libvsomeip3.so.3 => /usr/local/lib/libvsomeip3.so.3 (0x0000ffff80310000)
	libboost_filesystem.so.1.74.0 => /lib/aarch64-linux-gnu/libboost_filesystem.so.1.74.0 (0x0000ffff802c0000)
	libstdc++.so.6 => /lib/aarch64-linux-gnu/libstdc++.so.6 (0x0000ffff80090000)
	libgcc_s.so.1 => /lib/aarch64-linux-gnu/libgcc_s.so.1 (0x0000ffff80060000)
	libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000ffff7feb0000)
	/lib/ld-linux-aarch64.so.1 (0x0000ffff80628000)
	libboost_thread.so.1.74.0 => /lib/aarch64-linux-gnu/libboost_thread.so.1.74.0 (0x0000ffff7fe70000)
	libm.so.6 => /lib/aarch64-linux-gnu/libm.so.6 (0x0000ffff7fdd0000)

**Comment by Hithesh0899** [comment]
> @wangjingxiaomidou you need to read the readme files, and all the steps indicated in the comments. https://github.com/COVESA/vsomeip/blob/70d59edc01c9978ada66615c033e941e40561bb6/examples/hello_world/readme VSOMEIP_CONFIGURATION and VSOMEIP_APPLICATION_NAME are necessary

Yes i have did the same as per the steps but issue is not getting resolved, please suggest the next steps, thanks  - Hithesh

**Comment by wangjingxiaomidou** [comment]
@Hithesh0899 what version of linux do you use? Mine is ubuntu 22.04 arm processor.

**Comment by Hithesh0899** [comment]
Hi @wangjingxiaomidou I am using Ubuntu 20.04, Intel x86_64 processor

**Comment by wangjingxiaomidou** [comment]
Hi, @Hithesh0899 @goncaloalmeida : I have found the solution.
Actually, I add log in the vsomeip code and find dlopen is failed. I use the “dlerror” to print the error. And the result is that  the error “undefined symbol _zn5boost10filesystem6detail11dir_itr_impd1ev” happened.
![image](https://github.com/COVESA/vsomeip/assets/58726252/407bd21f-e658-426d-8e42-6903377e2aa1)
![image](https://github.com/COVESA/vsomeip/assets/58726252/be6e265c-2cef-4126-bcf3-630d245fdec7)

 So my solution is reinstall the boost based on https://www.boost.org/doc/libs/1_83_0/more/getting_started/unix-variants.html
cd path/to/boost_1_83_0
$ ./bootstrap.sh --help
./bootstrap.sh --prefix=/usr/local
./b2 install

And then, I recompile vsomeip. It works well.
<img width="742" alt="image" src="https://github.com/COVESA/vsomeip/assets/58726252/2173f45c-a164-4909-af9f-0617b4359c3b">
Hope it is useful for you.

**Comment by Hithesh0899** [comment]
hi @wangjingxiaomidou, so just i have to follow this steps to reinstall ?
cd path/to/boost_1_83_0
$ ./bootstrap.sh --help
./bootstrap.sh --prefix=/usr/local
./b2 install
2. I have to rebuild the vsomeip from git ? is it the resolution, please confirm thank you

**Comment by wangjingxiaomidou** [comment]
Yes, Which country do you come from? Maybe we can talk offline.



506480019
***@***.***







                       
Original Email
                       
                     

Sender:"Hithesh0899"< ***@***.*** &gt;;

Sent Time:2023/11/15 15:07

To:"COVESA/vsomeip"< ***@***.*** &gt;;

Cc recipient:"wangjingxiaomidou"< ***@***.*** &gt;;"Mention"< ***@***.*** &gt;;

Subject:Re: [COVESA/vsomeip] ~/vsomeip/examples/hello_world$VSOMEIP_CONFIGURATION=./helloworld-local.jsonVSOMEIP_APPLICATION_NAME=hello_world_service ./hello_world_service  1Configuration module could not be loaded! (Issue #569)




 
hi @wangjingxiaomidou, so just i have to follow this steps to reinstall ?
 cd path/to/boost_1_83_0
 $ ./bootstrap.sh --help
 ./bootstrap.sh --prefix=/usr/local
 ./b2 install
 2. I have to rebuild the vsomeip from git ? is it the resolution, please confirm thank you

**Comment by wangjingxiaomidou** [comment]
@Hithesh0899 Yes

**Comment by Hithesh0899** [comment]
Thank you, i will check and come back to you..

**Comment by wangjingxiaomidou** [comment]
> ./bootstrap.sh --help

The downloadable file
