### ISSUE TITLE
uid/gid crendential types on QNX 7.1 wot v3.4.9

### ISSUE THREAD

**Issue by kheaactua** [COVESA/vsomeip#574]
I see that 3.4.9 has started integrating QNX 7.1 support.  The source seems to be specifiying [wrong] types for the uid/gid though.  For instance, in https://github.com/COVESA/vsomeip/blob/70d59edc01c9978ada66615c033e941e40561bb6/interface/vsomeip/primitive_types.hpp#L59-L65

This type is defined by QNX already in `$QNX_TARGET/usr/include/sys/target_nto.h`, for me it's:
```sh
❯ rg UID_T $QNX_TARGET/usr/include/sys/target_nto.h
49:#undef __UID_T
50:#define __UID_T              _INT32
```

There are then many includes (`stat.h`, `types.h`, _etc_) that do:
```cpp
#if defined(__UID_T)
typedef __UID_T              uid_t;
#undef __UID_T
#endif
```

By contrast, capicxx-core-runtime does this properly: https://github.com/COVESA/capicxx-core-runtime/blob/c4351ee6972890b225ec9d4984c8f4fa9dd09ae8/include/CommonAPI/Types.hpp#L92-L98

Is there any reason vsomeip is attempting to change the type?  I think sticking to the platform defined type is much safer.  I've also prepared https://github.com/COVESA/vsomeip/pull/561 to use the types more consistently throughout vsomeip.  I haven't removed the lines in `primitive_types.hpp` yet but will probably do so - I just wanted to first ask if there was a reason.

**Comment by kheaactua** [comment]
Thanks for the reply.  I wish I had have known about that PR while it was under development.  My group has been maintaining QNX ports for a few years now and likely had a lot to contribute.

About the uid being a bad type though, how to you suggest I pursue this?  Just open a PR and cite https://github.com/COVESA/vsomeip/pull/447 ?

**Comment by fcmonteiro** [comment]
You can still contribute to the QNX support and vSomeIP, if you have suggestions to improve the current QNX implementation please create a PR with the changes.
Regarding the uid stuff, is probably easier if you update your PR #561, or close that one and create a new one.
