### ISSUE TITLE
Running Sample Hello-World: /usr/local/lib/libvsomeip3.so.3.4.9: error adding symbols: file in wrong format

### ISSUE THREAD

**Issue by kpit-vijay** [COVESA/vsomeip#577]
**My configuration:**

**ubuntu@ip-10-56-2-41:~** uname -a
Linux ip-10-56-2-41 6.2.0-1015-aws #15~22.04.1-Ubuntu SMP Fri Oct  6 21:37:24 UTC 2023 **x86_64 x86_64 x86_64** GNU/Linux

**Error I am facing:**

**ubuntu@ip-10-56-2-41:~/vsomeip/examples/hello_world/build$** make
[ 25%] Linking CXX executable hello_world_service
**/usr/bin/ld: /usr/local/lib/libvsomeip3.so.3.4.9: error adding symbols: file in wrong format**
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/hello_world_service.dir/build.make:98: hello_world_service] Error 1
make[1]: *** [CMakeFiles/Makefile2:85: CMakeFiles/hello_world_service.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

**Found that the libvsomeip file that I have is for aarch64 while I am trying to build project for Ubuntu 22.04 amd64:**

**ubuntu@ip-10-56-2-41:~**/vsomeip/examples/hello_world/build$ file /usr/local/lib/libvsomeip3.so.3.4.9
/usr/local/lib/libvsomeip3.so.3.4.9: ELF 64-bit LSB shared object, **ARM aarch64**, version 1 (SYSV), dynamically linked, BuildID[sha1]=fc2a47ac3ac8efb4d59c89b1cc3afab95c2ca65d, with debug_info, not stripped

Should I try using Ubuntu with aarch64 architecture to run the sample examples successfully? Can anyone clarify if anything I am missing here?

**Comment by reymor** [comment]
Hello,

There is no need of using Ubuntu aarch64. How do you compile your libraries?
