### ISSUE TITLE
Calling stop() while the vsomeip application is running (blocking start())

### ISSUE THREAD

**Issue by nkuang123** [COVESA/vsomeip#587]
I am currently using vsomeip 3.4.10 and had a few questions regarding application development.

1. As the documentation states, `vsomeip::application::start()` is a blocking IO call:

> This method must be called after init to start message processing. **It will block until the message processing is terminated using the stop method or by receiving signals.** It processes messages received via the sockets and uses registered callbacks to pass them to the user application.

What is the ideal way to terminate this function call in a single-threaded context? For instance let's say the client subscribed to an event and began receiving messages for an indefinite amount of time; if the client then wants to unsubscribe and stop the application entirely, what is the best way of doing this? 

Ideally I would use something like the `process()` function to manually process incoming messages but it's not implemented.

2. When a client subscribes to an event, is the subscription performed on every offer received from the server? From the Subscribe example in _vsome in 10 minutes_, it looks like the `subscribe()` function call is called only once and is invoked on every offer received from the server. Just wanted to confirm this.

Thanks

**Comment by anaritarodrigues** [comment]
Hi @nkuang123 ,

1. you can follow the example in https://github.com/COVESA/vsomeip/blob/master/examples/hello_world/hello_world_client.hpp . The best way to stop interely the application is:
```c++
void stop()
    {
        // unregister the state handler
        app_->unregister_state_handler();
        // unregister the message handler
        app_->unregister_message_handler(vsomeip::ANY_SERVICE,
                service_instance_id, vsomeip::ANY_METHOD);
        // alternatively unregister all registered handlers at once
        app_->clear_all_handler();
        // release the service
        app_->release_service(service_id, service_instance_id);
        // shutdown the application
        app_->stop();
    }
``` 
2. That's right. The subscribe() function is called only once. The application is registered as a requester of the service and the routing manager takes care of it from here. The routing manager will send a Subscribe request for each OfferService received, and will inform the application if the service becomes unavailable.
