### ISSUE TITLE
cppcheck errors

### ISSUE THREAD

**Issue by maingig** [COVESA/vsomeip#59]
Running this cppcheck command produces a number of warnings (2.14.16)
`cppcheck --force --quiet --enable=warning,style,performance,portability,information,missingInclude --inconclusive --suppress=missingIncludeSystem . 2> err.txt`

[err.txt](https://github.com/GENIVI/vsomeip/files/3448774/err.txt)

Updated against latest version.

**Comment by fcmonteiro** [comment]
Hi,
Are there any of these warnings that you think are important for us to solve?
We are already aware of some of them, as we are using SonarQube to fix some of them.
Thanks

cc: @goncaloalmeida
