### ISSUE TITLE
Communication between 2 Devives

### ISSUE THREAD

**Issue by akashnagpalofficial** [COVESA/vsomeip#590]
Hey there,

I'm currently working with two devices:

1. QNX OS with vSomeIp v3.1.20.3
2. Pi OS with vSomeIp v3.4.10

I've been experimenting with `subscribe-sample.cpp` and `notify-sample.cpp` on both terminals. Although there are no visible errors in either terminal, it seems the communication isn't functioning.

Has anyone successfully managed to make this work with the mentioned device combination? Oddly enough, I can execute the code flawlessly on the same node.

Any insights, suggestions, or experiences shared regarding this issue would be incredibly helpful. Thanks in advance for your assistance!

Best regards,
Akash Nagpal

**Comment by reymor** [comment]
Hello @akashnagpalofficial 

There are a lot of things that could be wrong and you are not providing enough information. I could suggest to use a network packet analyzer in one side like wireshark/tshark/tcpdump. 

Have you create the route?, I mean you have a service discovery which sends messages by a multicast IP. Assuming that you are running the service discovery in both devices. 

What is you .json communication? 

Check this: [Communication between two devices](https://github.com/COVESA/vsomeip/wiki/vsomeip-in-10-minutes#communication-between-two-devices)

**Comment by duartenfonseca** [comment]
closed due to no response from reporter
