### ISSUE TITLE
Own serialization/deserialization

### ISSUE THREAD

**Issue by icegood** [COVESA/vsomeip#610]
vsomeip has its own class to serialize/deserialize messages 
deserializer/serializer and even external payload is supposed to be serializable/deserializable with the help of it. However in practice, no one uses it as these classes are not exportable, which makes the whole library incomplete. To make the solution complete CommonApi introduces InputStream/OutputStream.

Make these classes public and and do not make consumers find own serialization/deserialization solutions w/o usage of external entities like commonAPI

**Comment by goncaloalmeida** [comment]
@icegood please open a new discussion and show some example of what you want to achive and how. thanks!
