### ISSUE TITLE
where is vsomeip_sec_client_t-aware?

### ISSUE THREAD

**Issue by fengmao31** [COVESA/vsomeip#612]
```warning: ‘virtual void vsomeip_v3::application::register_subscription_handler(vsomeip_v3::service_t, vsomeip_v3::instance_t, vsomeip_v3::eventgroup_t, const subscription_handler_t&)’ is deprecated: Use vsomeip_sec_client_t-aware functions and types instead. [-Wdeprecated-declarations]```

**Comment by BrunoLSilvaCTW** [comment]
Hi @fengmao31,

The `vsomeip_sec_client_t`-aware method is [here](https://github.com/COVESA/vsomeip/blob/55284c518f805a2e0194e23770f7c0f2b352ed64/interface/vsomeip/application.hpp#L1075).

**Comment by fengmao31** [comment]
what is the means of vsomeip_sec_client_t? At first, I think it is a new implainment function.
