### ISSUE TITLE
boost::asio::steady_timer not work

### ISSUE THREAD

**Issue by yanxiaochun1005** [COVESA/vsomeip#643]
### vSomeip Version

v3.1.20.3

### Boost Version

1.73

### Environment

Ubuntu 22.04

### Describe the bug

client_endpoint_impl.cpp train_.departure_timer_->async_wait(
            std::bind(&client_endpoint_impl<Protocol>::flush_cbk,
                      this->shared_from_this(), std::placeholders::_1));   flush_cbk not work，still block.

**Comment by BrunoLSilvaCTW** [comment]
Hi @yanxiaochun1005,

We no longer support vSomeIP version 3.1.20.3.

Please, use the latest version (3.4.10), and check if the issue persists.

Thanks.
