### ISSUE TITLE
[BUG]: How to enable someip to communicate between docker container and non container application 

### ISSUE THREAD

**Issue by shubham25091998** [COVESA/vsomeip#680]
### vSomeip Version

3.4.10

### Boost Version

1.71

### Environment

Ubuntu 20.04

### Describe the bug

I tried a communication between someip server application running in docker container with someip client application running directly as normal process. I have connected docker container to host network also, but no communication is happening between client and server.
Client and server able to communicate when both run in container.
So, is there any way in when docker and non docker application communicate over someip.

**Comment by giovanniojan** [comment]
as a workaround, I suggest you to bind /tmp host folder to guest (see https://docs.docker.com/storage/bind-mounts/) ; in this case the communication will be made via unix domain sockets

**Comment by goncaloalmeida** [comment]
@shubham25091998 this is not a defect/bug. Please use the discussion tab
