### ISSUE TITLE
[BUG]: <title>vSomeip build error

### ISSUE THREAD

**Issue by duanduanlin** [COVESA/vsomeip#683]
### vSomeip Version

v3.1.20.3

### Boost Version

1.74

### Environment

Embebdeb linux

### Describe the bug

 ./vsomeip/build_vsomeip.sh                 
-- The C compiler identification is GNU 4.9.3
-- The CXX compiler identification is GNU 4.9.3
-- Check for working C compiler: /home/dding3/work/mpu/jbox02/jbox02/external/sdk/ql_ec20/a07/ql-ol-crosstool/sysroots/x86_64-oesdk-linux/usr/bin/arm-oe-linux-gnueabi/arm-oe-linux-gnueabi-gcc
-- Check for working C compiler: /home/dding3/work/mpu/jbox02/jbox02/external/sdk/ql_ec20/a07/ql-ol-crosstool/sysroots/x86_64-oesdk-linux/usr/bin/arm-oe-linux-gnueabi/arm-oe-linux-gnueabi-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /home/dding3/work/mpu/jbox02/jbox02/external/sdk/ql_ec20/a07/ql-ol-crosstool/sysroots/x86_64-oesdk-linux/usr/bin/arm-oe-linux-gnueabi/arm-oe-linux-gnueabi-g++
-- Check for working CXX compiler: /home/dding3/work/mpu/jbox02/jbox02/external/sdk/ql_ec20/a07/ql-ol-crosstool/sysroots/x86_64-oesdk-linux/usr/bin/arm-oe-linux-gnueabi/arm-oe-linux-gnueabi-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting build type to 'RelWithDebInfo' as none was specified.
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Boost 1.55 found.
-- Found Boost components:
   system;thread;filesystem
-- Using boost version: 107400
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'automotive-dlt >= 2.11'
--   No package 'automotive-dlt' found
-- Checking for module 'libsystemd'
--   No package 'libsystemd' found
-- Systemd was not found, watchdog disabled!
-- Default configuration folder: /etc/vsomeip
-- Default configuration file: /etc/vsomeip.json
Predefined base path: /tmp
Predefined unicast address: 127.0.0.1
Predefined diagnosis address: 0x01
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.11") found components:  doxygen dot 
dot found
asciidoc found
source-highlight found
-- GTEST_ROOT is not defined. For building the tests the variable
             GTEST_ROOT has to be defined. Tests can not be built.
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    BOOST_ROOT
    Boost_NO_SYSTEM_PATHS

-- Build files have been written to: /home/dding3/work/mpu/jbox02/jbox02/3rdlibs/platforms/ql_ec20/build/objs/vsomeip-3.1.20.3/build
Scanning dependencies of target vsomeip3
[  1%] Building CXX object CMakeFiles/vsomeip3.dir/implementation/endpoints/src/client_endpoint_impl.cpp.o
[  2%] Building CXX object CMakeFiles/vsomeip3.dir/implementation/endpoints/src/credentials.cpp.o
[  3%] Building CXX object CMakeFiles/vsomeip3.dir/implementation/endpoints/src/endpoint_definition.cpp.o
[  4%] Building CXX object CMakeFiles/vsomeip3.dir/implementation/endpoints/src/endpoint_impl.cpp.o
[  5%] Building CXX object CMakeFiles/vsomeip3.dir/implementation/endpoints/src/endpoint_manager_base.cpp.o
[  6%] Building CXX object CMakeFiles/vsomeip3.dir/implementation/endpoints/src/endpoint_manager_impl.cpp.o
[  8%] Building CXX object CMakeFiles/vsomeip3.dir/implementation/endpoints/src/local_client_endpoint_impl.cpp.o
[  9%] Building CXX object CMakeFiles/vsomeip3.dir/implementation/endpoints/src/local_server_endpoint_impl.cpp.o
[ 10%] Building CXX object CMakeFiles/vsomeip3.dir/implementation/endpoints/src/netlink_connector.cpp.o
[ 11%] Building CXX object CMakeFiles/vsomeip3.dir/implementation/endpoints/src/server_endpoint_impl.cpp.o
In file included from /home/dding3/work/mpu/jbox02/jbox02/3rdlibs/platforms/ql_ec20/build/objs/vsomeip-3.1.20.3/implementation/endpoints/src/../include/server_endpoint_impl.hpp:20:0,
                 from /home/dding3/work/mpu/jbox02/jbox02/3rdlibs/platforms/ql_ec20/build/objs/vsomeip-3.1.20.3/implementation/endpoints/src/server_endpoint_impl.cpp:20:
/home/dding3/work/mpu/jbox02/jbox02/3rdlibs/platforms/ql_ec20/build/objs/vsomeip-3.1.20.3/implementation/endpoints/src/server_endpoint_impl.cpp: In instantiation of 'vsomeip_v3::server_endpoint_impl<Protocol>::send_cbk(vsomeip_v3::server_endpoint_impl<Protocol>::queue_iterator_type, const boost::system::error_code&, std::size_t)::<lambda()> [with Protocol = boost::asio::local::stream_protocol_ext]':
/home/dding3/work/mpu/jbox02/jbox02/3rdlibs/platforms/ql_ec20/build/objs/vsomeip-3.1.20.3/implementation/endpoints/src/server_endpoint_impl.cpp:612:36:   required from 'struct vsomeip_v3::server_endpoint_impl<Protocol>::send_cbk(vsomeip_v3::server_endpoint_impl<Protocol>::queue_iterator_type, const boost::system::error_code&, std::size_t) [with Protocol = boost::asio::local::stream_protocol_ext; vsomeip_v3::server_endpoint_impl<Protocol>::queue_iterator_type = std::_Rb_tree_iterator<std::pair<const boost::asio::local::basic_endpoint<boost::asio::local::stream_protocol_ext>, std::pair<unsigned int, std::deque<std::shared_ptr<std::vector<unsigned char> > > > > >; std::size_t = unsigned int]::<lambda()>'
/home/dding3/work/mpu/jbox02/jbox02/3rdlibs/platforms/ql_ec20/build/objs/vsomeip-3.1.20.3/implementation/endpoints/src/server_endpoint_impl.cpp:647:5:   required from 'void vsomeip_v3::server_endpoint_impl<Protocol>::send_cbk(vsomeip_v3::server_endpoint_impl<Protocol>::queue_iterator_type, const boost::system::error_code&, std::size_t) [with Protocol = boost::asio::local::stream_protocol_ext; vsomeip_v3::server_endpoint_impl<Protocol>::queue_iterator_type = std::_Rb_tree_iterator<std::pair<const boost::asio::local::basic_endpoint<boost::asio::local::stream_protocol_ext>, std::pair<unsigned int, std::deque<std::shared_ptr<std::vector<unsigned char> > > > > >; std::size_t = unsigned int]'
/home/dding3/work/mpu/jbox02/jbox02/3rdlibs/platforms/ql_ec20/build/objs/vsomeip-3.1.20.3/implementation/endpoints/src/server_endpoint_impl.cpp:769:16:   required from here
/home/dding3/work/mpu/jbox02/jbox02/3rdlibs/platforms/ql_ec20/build/objs/vsomeip-3.1.20.3/implementation/endpoints/src/../include/endpoint_impl.hpp:74:30: error: 'boost::asio::io_service& vsomeip_v3::endpoint_impl<boost::asio::local::stream_protocol_ext>::service_' is protected
     boost::asio::io_service &service_;
                              ^
/home/dding3/work/mpu/jbox02/jbox02/3rdlibs/platforms/ql_ec20/build/objs/vsomeip-3.1.20.3/implementation/endpoints/src/server_endpoint_impl.cpp:639:17: error: within this context
                 endpoint_impl<Protocol>::
                 ^
/home/dding3/work/mpu/jbox02/jbox02/3rdlibs/platforms/ql_ec20/build/objs/vsomeip-3.1.20.3/implementation/endpoints/src/server_endpoint_impl.cpp: In instantiation of 'void vsomeip_v3::server_endpoint_impl<Protocol>::send_cbk(vsomeip_v3::server_endpoint_impl<Protocol>::queue_iterator_type, const boost::system::error_code&, std::size_t) [with Protocol = boost::asio::local::stream_protocol_ext; vsomeip_v3::server_endpoint_impl<Protocol>::queue_iterator_type = std::_Rb_tree_iterator<std::pair<const boost::asio::local::basic_endpoint<boost::asio::local::stream_protocol_ext>, std::pair<unsigned int, std::deque<std::shared_ptr<std::vector<unsigned char> > > > > >; std::size_t = unsigned int]':
/home/dding3/work/mpu/jbox02/jbox02/3rdlibs/platforms/ql_ec20/build/objs/vsomeip-3.1.20.3/implementation/endpoints/src/server_endpoint_impl.cpp:769:16:   required from here
/home/dding3/work/mpu/jbox02/jbox02/3rdlibs/platforms/ql_ec20/build/objs/vsomeip-3.1.20.3/implementation/endpoints/src/server_endpoint_impl.cpp:693:43: error: invalid use of 'auto'
             check_if_all_queues_are_empty();
                                           ^
/home/dding3/work/mpu/jbox02/jbox02/3rdlibs/platforms/ql_ec20/build/objs/vsomeip-3.1.20.3/implementation/endpoints/src/server_endpoint_impl.cpp:734:47: error: invalid use of 'auto'
                 check_if_all_queues_are_empty();
                                               ^
In file included from /home/dding3/work/mpu/jbox02/jbox02/3rdlibs/platforms/ql_ec20/build/objs/vsomeip-3.1.20.3/implementation/endpoints/src/../include/server_endpoint_impl.hpp:20:0,
                 from /home/dding3/work/mpu/jbox02/jbox02/3rdlibs/platforms/ql_ec20/build/objs/vsomeip-3.1.20.3/implementation/endpoints/src/server_endpoint_impl.cpp:20:
/home/dding3/work/mpu/jbox02/jbox02/3rdlibs/platforms/ql_ec20/build/objs/vsomeip-3.1.20.3/implementation/endpoints/src/server_endpoint_impl.cpp: In instantiation of 'vsomeip_v3::server_endpoint_impl<Protocol>::send_cbk(vsomeip_v3::server_endpoint_impl<Protocol>::queue_iterator_type, const boost::system::error_code&, std::size_t)::<lambda()> [with Protocol = boost::asio::ip::tcp]':
/home/dding3/work/mpu/jbox02/jbox02/3rdlibs/platforms/ql_ec20/build/objs/vsomeip-3.1.20.3/implementation/endpoints/src/server_endpoint_impl.cpp:612:36:   required from 'struct vsomeip_v3::server_endpoint_impl<Protocol>::send_cbk(vsomeip_v3::server_endpoint_impl<Protocol>::queue_iterator_type, const boost::system::error_code&, std::size_t) [with Protocol = boost::asio::ip::tcp; vsomeip_v3::server_endpoint_impl<Protocol>::queue_iterator_type = std::_Rb_tree_iterator<std::pair<const boost::asio::ip::basic_endpoint<boost::asio::ip::tcp>, std::pair<unsigned int, std::deque<std::shared_ptr<std::vector<unsigned char> > > > > >; std::size_t = unsigned int]::<lambda()>'
/home/dding3/work/mpu/jbox02/jbox02/3rdlibs/platforms/ql_ec20/build/objs/vsomeip-3.1.20.3/implementation/endpoints/src/server_endpoint_impl.cpp:647:5:   required from 'void vsomeip_v3::server_endpoint_impl<Protocol>::send_cbk(vsomeip_v3::server_endpoint_impl<Protocol>::queue_iterator_type, const boost::system::error_code&, std::size_t) [with Protocol = boost::asio::ip::tcp; vsomeip_v3::server_endpoint_impl<Protocol>::queue_iterator_type = std::_Rb_tree_iterator<std::pair<const boost::asio::ip::basic_endpoint<boost::asio::ip::tcp>, std::pair<unsigned int, std::deque<std::shared_ptr<std::vector<unsigned char> > > > > >; std::size_t = unsigned int]'
/home/dding3/work/mpu/jbox02/jbox02/3rdlibs/platforms/ql_ec20/build/objs/vsomeip-3.1.20.3/implementation/endpoints/src/server_endpoint_impl.cpp:771:16:   required from here
/home/dding3/work/mpu/jbox02/jbox02/3rdlibs/platforms/ql_ec20/build/objs/vsomeip-3.1.20.3/implementation/endpoints/src/../include/endpoint_impl.hpp:74:30: error: 'boost::asio::io_service& vsomeip_v3::endpoint_impl<boost::asio::ip::tcp>::service_' is protected
     boost::asio::io_service &service_;
                              ^
/home/dding3/work/mpu/jbox02/jbox02/3rdlibs/platforms/ql_ec20/build/objs/vsomeip-3.1.20.3/implementation/endpoints/src/server_endpoint_impl.cpp:639:17: error: within this context
                 endpoint_impl<Protocol>::
                 ^
/home/dding3/work/mpu/jbox02/jbox02/3rdlibs/platforms/ql_ec20/build/objs/vsomeip-3.1.20.3/implementation/endpoints/src/server_endpoint_impl.cpp: In instantiation of 'void vsomeip_v3::server_endpoint_impl<Protocol>::send_cbk(vsomeip_v3::server_endpoint_impl<Protocol>::queue_iterator_type, const boost::system::error_code&, std::size_t) [with Protocol = boost::asio::ip::tcp; vsomeip_v3::server_endpoint_impl<Protocol>::queue_iterator_type = std::_Rb_tree_iterator<std::pair<const boost::asio::ip::basic_endpoint<boost::asio::ip::tcp>, std::pair<unsigned int, std::deque<std::shared_ptr<std::vector<unsigned char> > > > > >; std::size_t = unsigned int]':
/home/dding3/work/mpu/jbox02/jbox02/3rdlibs/platforms/ql_ec20/build/objs/vsomeip-3.1.20.3/implementation/endpoints/src/server_endpoint_impl.cpp:771:16:   required from here
/home/dding3/work/mpu/jbox02/jbox02/3rdlibs/platforms/ql_ec20/build/objs/vsomeip-3.1.20.3/implementation/endpoints/src/server_endpoint_impl.cpp:693:43: error: invalid use of 'auto'
             check_if_all_queues_are_empty();
                                           ^
/home/dding3/work/mpu/jbox02/jbox02/3rdlibs/platforms/ql_ec20/build/objs/vsomeip-3.1.20.3/implementation/endpoints/src/server_endpoint_impl.cpp:734:47: error: invalid use of 'auto'
                 check_if_all_queues_are_empty();
                                               ^
In file included from /home/dding3/work/mpu/jbox02/jbox02/3rdlibs/platforms/ql_ec20/build/objs/vsomeip-3.1.20.3/implementation/endpoints/src/../include/server_endpoint_impl.hpp:20:0,
                 from /home/dding3/work/mpu/jbox02/jbox02/3rdlibs/platforms/ql_ec20/build/objs/vsomeip-3.1.20.3/implementation/endpoints/src/server_endpoint_impl.cpp:20:
/home/dding3/work/mpu/jbox02/jbox02/3rdlibs/platforms/ql_ec20/build/objs/vsomeip-3.1.20.3/implementation/endpoints/src/server_endpoint_impl.cpp: In instantiation of 'vsomeip_v3::server_endpoint_impl<Protocol>::send_cbk(vsomeip_v3::server_endpoint_impl<Protocol>::queue_iterator_type, const boost::system::error_code&, std::size_t)::<lambda()> [with Protocol = boost::asio::ip::udp_ext]':
/home/dding3/work/mpu/jbox02/jbox02/3rdlibs/platforms/ql_ec20/build/objs/vsomeip-3.1.20.3/implementation/endpoints/src/server_endpoint_impl.cpp:612:36:   required from 'struct vsomeip_v3::server_endpoint_impl<Protocol>::send_cbk(vsomeip_v3::server_endpoint_impl<Protocol>::queue_iterator_type, const boost::system::error_code&, std::size_t) [with Protocol = boost::asio::ip::udp_ext; vsomeip_v3::server_endpoint_impl<Protocol>::queue_iterator_type = std::_Rb_tree_iterator<std::pair<const boost::asio::ip::basic_endpoint<boost::asio::ip::udp>, std::pair<unsigned int, std::deque<std::shared_ptr<std::vector<unsigned char> > > > > >; std::size_t = unsigned int]::<lambda()>'
/home/dding3/work/mpu/jbox02/jbox02/3rdlibs/platforms/ql_ec20/build/objs/vsomeip-3.1.20.3/implementation/endpoints/src/server_endpoint_impl.cpp:647:5:   required from 'void vsomeip_v3::server_endpoint_impl<Protocol>::send_cbk(vsomeip_v3::server_endpoint_impl<Protocol>::queue_iterator_type, const boost::system::error_code&, std::size_t) [with Protocol = boost::asio::ip::udp_ext; vsomeip_v3::server_endpoint_impl<Protocol>::queue_iterator_type = std::_Rb_tree_iterator<std::pair<const boost::asio::ip::basic_endpoint<boost::asio::ip::udp>, std::pair<unsigned int, std::deque<std::shared_ptr<std::vector<unsigned char> > > > > >; std::size_t = unsigned int]'
/home/dding3/work/mpu/jbox02/jbox02/3rdlibs/platforms/ql_ec20/build/objs/vsomeip-3.1.20.3/implementation/endpoints/src/server_endpoint_impl.cpp:772:16:   required from here
/home/dding3/work/mpu/jbox02/jbox02/3rdlibs/platforms/ql_ec20/build/objs/vsomeip-3.1.20.3/implementation/endpoints/src/../include/endpoint_impl.hpp:74:30: error: 'boost::asio::io_service& vsomeip_v3::endpoint_impl<boost::asio::ip::udp_ext>::service_' is protected
     boost::asio::io_service &service_;
                              ^
/home/dding3/work/mpu/jbox02/jbox02/3rdlibs/platforms/ql_ec20/build/objs/vsomeip-3.1.20.3/implementation/endpoints/src/server_endpoint_impl.cpp:639:17: error: within this context
                 endpoint_impl<Protocol>::
                 ^
/home/dding3/work/mpu/jbox02/jbox02/3rdlibs/platforms/ql_ec20/build/objs/vsomeip-3.1.20.3/implementation/endpoints/src/server_endpoint_impl.cpp: In instantiation of 'void vsomeip_v3::server_endpoint_impl<Protocol>::send_cbk(vsomeip_v3::server_endpoint_impl<Protocol>::queue_iterator_type, const boost::system::error_code&, std::size_t) [with Protocol = boost::asio::ip::udp_ext; vsomeip_v3::server_endpoint_impl<Protocol>::queue_iterator_type = std::_Rb_tree_iterator<std::pair<const boost::asio::ip::basic_endpoint<boost::asio::ip::udp>, std::pair<unsigned int, std::deque<std::shared_ptr<std::vector<unsigned char> > > > > >; std::size_t = unsigned int]':
/home/dding3/work/mpu/jbox02/jbox02/3rdlibs/platforms/ql_ec20/build/objs/vsomeip-3.1.20.3/implementation/endpoints/src/server_endpoint_impl.cpp:772:16:   required from here
/home/dding3/work/mpu/jbox02/jbox02/3rdlibs/platforms/ql_ec20/build/objs/vsomeip-3.1.20.3/implementation/endpoints/src/server_endpoint_impl.cpp:693:43: error: invalid use of 'auto'
             check_if_all_queues_are_empty();
                                           ^
/home/dding3/work/mpu/jbox02/jbox02/3rdlibs/platforms/ql_ec20/build/objs/vsomeip-3.1.20.3/implementation/endpoints/src/server_endpoint_impl.cpp:734:47: error: invalid use of 'auto'
                 check_if_all_queues_are_empty();
                                               ^
In file included from /home/dding3/work/mpu/jbox02/jbox02/3rdlibs/platforms/ql_ec20/build/rootfs/apps/include/boost/asio/io_context.hpp:1519:0,
                 from /home/dding3/work/mpu/jbox02/jbox02/3rdlibs/platforms/ql_ec20/build/rootfs/apps/include/boost/asio/detail/io_object_impl.hpp:23,
                 from /home/dding3/work/mpu/jbox02/jbox02/3rdlibs/platforms/ql_ec20/build/rootfs/apps/include/boost/asio/basic_socket.hpp:22,
                 from /home/dding3/work/mpu/jbox02/jbox02/3rdlibs/platforms/ql_ec20/build/rootfs/apps/include/boost/asio/basic_socket_acceptor.hpp:20,
                 from /home/dding3/work/mpu/jbox02/jbox02/3rdlibs/platforms/ql_ec20/build/rootfs/apps/include/boost/asio/ip/tcp.hpp:19,
                 from /home/dding3/work/mpu/jbox02/jbox02/3rdlibs/platforms/ql_ec20/build/objs/vsomeip-3.1.20.3/implementation/endpoints/src/server_endpoint_impl.cpp:13:
/home/dding3/work/mpu/jbox02/jbox02/3rdlibs/platforms/ql_ec20/build/rootfs/apps/include/boost/asio/impl/io_context.hpp:199:1: error: 'typename boost::asio::async_result<typename std::decay<_Tp>::type, void()>::return_type boost::asio::io_context::post(LegacyCompletionHandler&&) [with LegacyCompletionHandler = vsomeip_v3::server_endpoint_impl<Protocol>::send_cbk(vsomeip_v3::server_endpoint_impl<Protocol>::queue_iterator_type, const boost::system::error_code&, std::size_t)::<lambda()> [with Protocol = boost::asio::local::stream_protocol_ext]::<lambda()>; typename boost::asio::async_result<typename std::decay<_Tp>::type, void()>::return_type = void]', declared using local type 'vsomeip_v3::server_endpoint_impl<Protocol>::send_cbk(vsomeip_v3::server_endpoint_impl<Protocol>::queue_iterator_type, const boost::system::error_code&, std::size_t)::<lambda()> [with Protocol = boost::asio::local::stream_protocol_ext]::<lambda()>', is used but never defined [-fpermissive]
 io_context::post(BOOST_ASIO_MOVE_ARG(LegacyCompletionHandler) handler)
 ^
/home/dding3/work/mpu/jbox02/jbox02/3rdlibs/platforms/ql_ec20/build/rootfs/apps/include/boost/asio/impl/io_context.hpp:199:1: error: 'typename boost::asio::async_result<typename std::decay<_Tp>::type, void()>::return_type boost::asio::io_context::post(LegacyCompletionHandler&&) [with LegacyCompletionHandler = vsomeip_v3::server_endpoint_impl<Protocol>::send_cbk(vsomeip_v3::server_endpoint_impl<Protocol>::queue_iterator_type, const boost::system::error_code&, std::size_t)::<lambda()> [with Protocol = boost::asio::ip::tcp]::<lambda()>; typename boost::asio::async_result<typename std::decay<_Tp>::type, void()>::return_type = void]', declared using local type 'vsomeip_v3::server_endpoint_impl<Protocol>::send_cbk(vsomeip_v3::server_endpoint_impl<Protocol>::queue_iterator_type, const boost::system::error_code&, std::size_t)::<lambda()> [with Protocol = boost::asio::ip::tcp]::<lambda()>', is used but never defined [-fpermissive]
/home/dding3/work/mpu/jbox02/jbox02/3rdlibs/platforms/ql_ec20/build/rootfs/apps/include/boost/asio/impl/io_context.hpp:199:1: error: 'typename boost::asio::async_result<typename std::decay<_Tp>::type, void()>::return_type boost::asio::io_context::post(LegacyCompletionHandler&&) [with LegacyCompletionHandler = vsomeip_v3::server_endpoint_impl<Protocol>::send_cbk(vsomeip_v3::server_endpoint_impl<Protocol>::queue_iterator_type, const boost::system::error_code&, std::size_t)::<lambda()> [with Protocol = boost::asio::ip::udp_ext]::<lambda()>; typename boost::asio::async_result<typename std::decay<_Tp>::type, void()>::return_type = void]', declared using local type 'vsomeip_v3::server_endpoint_impl<Protocol>::send_cbk(vsomeip_v3::server_endpoint_impl<Protocol>::queue_iterator_type, const boost::system::error_code&, std::size_t)::<lambda()> [with Protocol = boost::asio::ip::udp_ext]::<lambda()>', is used but never defined [-fpermissive]
CMakeFiles/vsomeip3.dir/build.make:179: recipe for target 'CMakeFiles/vsomeip3.dir/implementation/endpoints/src/server_endpoint_impl.cpp.o' failed
make[2]: *** [CMakeFiles/vsomeip3.dir/implementation/endpoints/src/server_endpoint_impl.cpp.o] Error 1
CMakeFiles/Makefile2:109: recipe for target 'CMakeFiles/vsomeip3.dir/all' failed
make[1]: *** [CMakeFiles/vsomeip3.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by goncaloalmeida** [comment]
vsomeip 3.1.* is no longer supported, please use a more recent version.
Thanks
