### ISSUE TITLE
[BUG]: Event registration with dynamic instances fails on routing node

### ISSUE THREAD

**Issue by wennmbj** [COVESA/vsomeip#684]
### vSomeip Version

v3.4.9.1

### Boost Version

1.78

### Environment

Embedded

### Describe the bug

With the usage of dynamic instance ids, the event is not correctly registered at the routing node in routing_manager_stub. A remote client is then not able to subscribe to an event (NACK). In the routing node the error process_eventgroupentry: Received a SubscribeEventGroup entry for unknown eventgroup from ... is shown.

### Expected behaviour

Event is registered at the routing node.

### Logs and Screenshots

![EventGroup_failure_dynamic_instance](https://github.com/COVESA/vsomeip/assets/118190520/9c64db4a-e921-440d-8429-32a4a77b3d4c)

**Comment by duartenfonseca** [comment]
@wennmbj could you add some reproduction steps for this error?

**Comment by duartenfonseca** [comment]
@wennmbj closing this as this is not a feature from vsomeip
