### ISSUE TITLE
Query regarding vsomeip3.1.20.3 compilation on Windows

### ISSUE THREAD

**Issue by srchaitu2008** [COVESA/vsomeip#686]
### vSomeip Version

v3.1.20.3

### Boost Version

1.81

### Environment

Windows 11

### Describe the bug

I am trying to compile vsomeip3.1.20.3(with boost 1.81) on Windows 11 using MSVC. I have observed that pthread detection fails since pthread is not available on Windows by default which is expected. Do I need to install pthreads on Windows to solve this or can we set CMAKE_HAVE_LIBC_PTHREAD to false for Windows ?

**Comment by goncaloalmeida** [comment]
vsomeip 3.1.* is no longer supported, please use a more recent version.
Thanks
