### ISSUE TITLE
[BUG]: Facing Issue while compiling vsomeip in gcc version 12.2.0 (Debian 12.2.0-14)

### ISSUE THREAD

**Issue by itsavi7879** [COVESA/vsomeip#715]
### vSomeip Version

#https://github.com/COVESA/vsomeip/commit/6c0e9db200fbcfd37879c4b2ff0c8523a29d8eb5

### Boost Version

1.74

### Environment

GCC version 12.2.0 (debian 12.2.0-14)

### Describe the bug

When i am trying to compile the vsomeip library in gcc 9.4.0 (ubuntu 9.4.0-1ubuntu1~20.04.2) i am able to compile vsomeip with below mentioned commands:-
**cd vsomeip
rm -rf build
mkdir build
cd build
cmake ..
make -j $(nproc)
make install**

it is compiling without throwing any error.
But when i try to run the same set of command in gcc version 12.2.0(Debian 12.2.0-14) , i am getting the error for which i have attached the screenshots.
ERROR: 
**inlined from 'bool vsomeip_v3::policy::deserialize(const vsomeip_v3::byte_t*&, uint32_t&)' at /tmp/vsomeip/implementation/security/src/policy.cpp:71:23:
/usr/include/boost/icl/detail/interval_set_algo.hpp:358:5: error: writing 9 bytes into a region of size 8 [-Werror=stringop-overflow=]
  358 |     const_cast<value_type&>(key_value<Type>(first_))**

### Reproduction Steps

**cd vsomeip
rm -rf build
mkdir build
cd build
cmake ..
make -j $(nproc)
make install**

### Expected behaviour

It should build successfully.
![image](https://github.com/COVESA/vsomeip/assets/152829008/4f2ce089-7b06-437f-b67f-8eb55fec7f9f)

### Logs and Screenshots

![vsomeip_error(1)](https://github.com/COVESA/vsomeip/assets/152829008/2851f9f3-99fc-470a-ae37-4ef00666b6dc)
![vsomeip_error(2)](https://github.com/COVESA/vsomeip/assets/152829008/748e5e9f-2533-48aa-83d4-1899017db039)

**Comment by phongt** [comment]
seem like same problem https://github.com/COVESA/vsomeip/issues/688

**Comment by duartenfonseca** [comment]
@itsavi7879 can you retry with a more recent version? thanks

**Comment by duartenfonseca** [comment]
no response in a month
