### ISSUE TITLE
[BUG]: <title>

### ISSUE THREAD

**Issue by liuzhiliuzhiwei** [COVESA/vsomeip#722]
### vSomeip Version

v3.4.10

### Boost Version

1.85

### Environment

QNX

### Describe the bug

在QNX系统中 创建一个服务端Proxy和一个客户端Proxy，客户端发起订阅但是收不到订阅确认

**Comment by goncaloalmeida** [comment]
@liuzhiliuzhiwei  title? logs? description in english.. thanks!

**Comment by duartenfonseca** [comment]
closing as no response was given
