### ISSUE TITLE
Someip sd communication issue when using ipv6

### ISSUE THREAD

**Issue by bouhamedayman** [COVESA/vsomeip#732]
### vSomeip Version

v3.4.0

### Boost Version

1.74

### Environment

Ubuntu 22.04

### Describe the bug

When I try to communicate two vsomeip application between two different machines (similar to vsomeip 10 minutes) but using ipv6 communication . I'm not getting any subscribe frome the client side as if the service is not available I'm using an ip multicast address ff14::4:0 . While when I use the IP ff02::1  the communication is well established . 

### Reproduction Steps

Same steps in https://github.com/COVESA/vsomeip/wiki/vsomeip-in-10-minutes but just using the mentioned IPs above . 

### Expected behaviour

Someip sd communication established .

**Comment by biggoldenbee** [comment]
#506 
#508

**Comment by wennmbj** [comment]
I had similar issues, please see my PR: https://github.com/COVESA/vsomeip/pull/608

**Comment by duartenfonseca** [comment]
hi @bouhamedayman try to update to 3.4.10 and retest, there has been a fix to this error

**Comment by bouhamedayman** [comment]
Helllo @duartenfonseca , I have fixed the issue by adding the multicast address to the local routing table .
