### ISSUE TITLE
[BUG]: No "set_protocol_version()" API found

### ISSUE THREAD

**Issue by Vignesh-Murugappan** [COVESA/vsomeip#767]
### vSomeip Version

v3.4.10

### Boost Version

1.76

### Environment

Ubuntu

### Describe the bug

No "set_protocol_version()" API found to set the protocol version other than 0x01.

As we have API for get_protocol_version() in https://github.com/COVESA/vsomeip/blob/fd7758c6e5823cdc64712b3b88a04c94d6fd0f0e/interface/vsomeip/message_base.hpp#L144, I feel we should have API for set as well.

Understood that protocol version is fixed, but still it would be better if we have API for set.

**Comment by duartenfonseca** [comment]
The protocol version depends on the implementation of the stack. As there is only one SOME/IP protocol version as far as we know, setting it to whatever value makes no sense. 

We will add it as soon as there exists and we (vsomeip) will support multiple protocol versions.
