### ISSUE TITLE
how can I verify if the E2E protection profile 4 is working correctly 

### ISSUE THREAD

**Issue by GHARBIAchref** [COVESA/vsomeip#769]
### vSomeip Version

v3.4.10

### Boost Version

1.83

### Environment

MSVC

### Describe the bug

how can I verify if the E2E protection profile 4 is working correctly in Wireshark

**Comment by duartenfonseca** [comment]
answered here: https://github.com/COVESA/vsomeip/issues/768#issuecomment-2370902523
