### ISSUE TITLE
why E2E Profile 4 and  Profile 5  can only be used for instances [1-255]"

### ISSUE THREAD

**Issue by GHARBIAchref** [COVESA/vsomeip#805]
### vSomeip Version

v3.4.10

### Boost Version

1.83

### Environment

windows 10

### Describe the bug

 why E2E Profile 4 and  Profile 5  can only be used for instances ### [1-255]"
  VSOMEIP_ERROR << "E2E Profile 4 can only be used for instances [1-255]";

**Comment by duartenfonseca** [comment]
do you have reproduction steps for the error?

**Comment by GHARBIAchref** [comment]
![e2e_instance](https://github.com/user-attachments/assets/755c3f86-c237-4106-b7f7-90e9543c0176)
When I try to apply the protection mechanism of profile 04 to a service that has an instance >255 , this error message appears, and the protection  Profile 04 does not apply.

**Comment by duartenfonseca** [comment]
do you have an instance value bigger than 255?
![image](https://github.com/user-attachments/assets/632f9626-50f7-40c5-8e00-569de2084ff5)
vsomeip-lib/implementation/e2e_protection/src/e2e/profile/profile04/checker.cpp::24

**Comment by GHARBIAchref** [comment]
@duartenfonseca   
Hello ,
  es, my application has an instance value greater than 255. Is it possible to apply the E2E P04 fetcher in this application?

**Comment by duartenfonseca** [comment]
i don't think it is possible. this was the way it was implemented. maybe you can try to use profile 7 or profile 1 which do not have that check.

**Comment by duartenfonseca** [comment]
this is implemented like this by design, it does not allow a bigger instance value than 255
