### ISSUE TITLE
[BUG]: Honor TMPDIR environment variable if defined for Linux systems

### ISSUE THREAD

**Issue by srchaitu2008** [COVESA/vsomeip#816]
### vSomeip Version

v3.4.10

### Boost Version

1.81

### Environment

Debian 11

### Describe the bug

​​Honor TMPDIR environment variable if defined for Linux systems to allow the vsomeip.lck and other temp files to be written in the path defined in TMPDIR env variable instead of default /tmp folder​.

**Comment by KareemLMR** [comment]
Hello @srchaitu2008 
I think it is already implemented here:
![image](https://github.com/user-attachments/assets/85093026-ba51-4128-9abf-b0daff916510)
You should just pass the TMPDIR you want to the cmake command as cmake -DBASE_PATH=<YOUR BASE PATH> ..

I found it also mentioned in the user guide here:
![image](https://github.com/user-attachments/assets/37c80776-5aef-4beb-9a50-4479e553a7f2)

**Comment by srchaitu2008** [comment]
Hi @KareemLMR ,

I agree with you. Whatever you have mentioned( cmake -DBASE_PATH= ) is **compile time** specific. The solution which I have submitted is **runtime specific** (i.e.) at **runtime** the **TMPDIR** environment variable will be checked and used if available, else the default path would be considered. 

I hope this clarifies your concern.

Thanks,
Ravi

**Comment by duartenfonseca** [comment]
@srchaitu2008 what is the use case where you have to do it like this? wouldn't it be enough being able to set this path on compile time?
